import { Tool, ApprovalRequest, Client } from './types';

// ─── Client registry ──────────────────────────────────────────────────────────

export const clients: Client[] = [
  { id: 'nexus', name: 'Nexus Systems', industry: 'B2B SaaS', employees: 125 },
  { id: 'orbit', name: 'Orbit Analytics', industry: 'Data & AI', employees: 45 },
  { id: 'cascade', name: 'Cascade Labs', industry: 'Software Dev', employees: 80 },
];

// ─── Nexus Systems ────────────────────────────────────────────────────────────
// 125-person B2B SaaS. Overlaps: PM, CRM, Docs, Design, Analytics, Security

const nexusTools: Tool[] = [
  { id: 'nx-1',  name: 'Slack',            category: 'Communication',      monthlyCost: 1250,  seats: 125, owner: 'IT',          renewalDate: '2026-03-15', status: 'active' },
  { id: 'nx-2',  name: 'Zoom',             category: 'Communication',      monthlyCost: 800,   seats: 100, owner: 'IT',          renewalDate: '2026-03-28', status: 'active' },
  { id: 'nx-3',  name: 'Loom',             category: 'Communication',      monthlyCost: 200,   seats: 40,  owner: 'Marketing',   renewalDate: '2026-05-20', status: 'active' },
  { id: 'nx-4',  name: 'Asana',            category: 'Project Management', monthlyCost: 1500,  seats: 80,  owner: 'Ops',         renewalDate: '2026-06-10', status: 'active' },
  { id: 'nx-5',  name: 'Monday.com',       category: 'Project Management', monthlyCost: 1100,  seats: 60,  owner: 'Engineering', renewalDate: '2026-07-22', status: 'review' },
  { id: 'nx-6',  name: 'Salesforce',       category: 'CRM',                monthlyCost: 4500,  seats: 50,  owner: 'Sales',       renewalDate: '2026-11-30', status: 'active' },
  { id: 'nx-7',  name: 'HubSpot',          category: 'CRM',                monthlyCost: 1800,  seats: 30,  owner: 'Marketing',   renewalDate: '2026-04-02', status: 'review' },
  { id: 'nx-8',  name: 'Intercom',         category: 'CRM',                monthlyCost: 1200,  seats: 20,  owner: 'Support',     renewalDate: '2026-08-15', status: 'review' },
  { id: 'nx-9',  name: 'Figma',            category: 'Design',             monthlyCost: 450,   seats: 15,  owner: 'Design',      renewalDate: '2026-10-12', status: 'active' },
  { id: 'nx-10', name: 'Miro',             category: 'Design',             monthlyCost: 320,   seats: 40,  owner: 'Product',     renewalDate: '2026-12-01', status: 'active' },
  { id: 'nx-11', name: 'Workday',          category: 'HR',                 monthlyCost: 3200,  seats: 125, owner: 'HR',          renewalDate: '2027-01-15', status: 'active' },
  { id: 'nx-12', name: 'Greenhouse',       category: 'HR',                 monthlyCost: 950,   seats: 20,  owner: 'HR',          renewalDate: '2026-09-01', status: 'active' },
  { id: 'nx-13', name: 'Notion',           category: 'Docs',               monthlyCost: 600,   seats: 120, owner: 'Product',     renewalDate: '2026-06-28', status: 'active' },
  { id: 'nx-14', name: 'Confluence',       category: 'Docs',               monthlyCost: 750,   seats: 90,  owner: 'Engineering', renewalDate: '2026-07-15', status: 'review' },
  { id: 'nx-15', name: 'Dropbox',          category: 'Docs',               monthlyCost: 420,   seats: 60,  owner: 'IT',          renewalDate: '2026-04-20', status: 'review' },
  { id: 'nx-16', name: 'DocuSign',         category: 'Other',              monthlyCost: 300,   seats: 10,  owner: 'Legal',       renewalDate: '2026-10-30', status: 'active' },
  { id: 'nx-17', name: '1Password',        category: 'Security',           monthlyCost: 375,   seats: 125, owner: 'IT',          renewalDate: '2026-04-01', status: 'active' },
  { id: 'nx-18', name: 'Okta',             category: 'Security',           monthlyCost: 1875,  seats: 125, owner: 'IT',          renewalDate: '2026-08-01', status: 'active' },
  { id: 'nx-19', name: 'GitHub',           category: 'Development',        monthlyCost: 1000,  seats: 60,  owner: 'Engineering', renewalDate: '2026-06-01', status: 'active' },
  { id: 'nx-20', name: 'Datadog',          category: 'Analytics',          monthlyCost: 2400,  seats: 30,  owner: 'DevOps',      renewalDate: '2026-09-15', status: 'active' },
  { id: 'nx-21', name: 'Tableau',          category: 'Analytics',          monthlyCost: 1400,  seats: 25,  owner: 'Data',        renewalDate: '2026-05-10', status: 'review' },
  { id: 'nx-22', name: 'PagerDuty',        category: 'Analytics',          monthlyCost: 600,   seats: 20,  owner: 'DevOps',      renewalDate: '2026-11-01', status: 'active' },
  { id: 'nx-23', name: 'Zendesk',          category: 'CRM',                monthlyCost: 1100,  seats: 15,  owner: 'Support',     renewalDate: '2026-05-30', status: 'review' },
  { id: 'nx-24', name: 'Stripe',           category: 'Other',              monthlyCost: 800,   seats: 5,   owner: 'Finance',     renewalDate: '2026-12-15', status: 'active' },
  { id: 'nx-25', name: 'Calendly',         category: 'Other',              monthlyCost: 180,   seats: 30,  owner: 'Sales',       renewalDate: '2026-07-01', status: 'active' },
];

const nexusRequests: ApprovalRequest[] = [
  {
    id: 'nx-req-1',
    toolName: 'Linear',
    category: 'Project Management',
    useCase: 'Engineering issue tracking — cleaner than Asana for dev workflows',
    estimatedMonthlyCost: 400,
    urgency: 'high',
    requester: 'Alex Chen',
    status: 'pending',
    submittedAt: '2026-02-28T10:00:00Z',
  },
  {
    id: 'nx-req-2',
    toolName: 'Grammarly Business',
    category: 'Other',
    useCase: 'Writing quality improvement for customer-facing content',
    estimatedMonthlyCost: 150,
    urgency: 'low',
    requester: 'Sarah Park',
    status: 'approved',
    submittedAt: '2026-02-15T14:30:00Z',
    reviewedAt: '2026-02-17T09:00:00Z',
    reviewerComment: 'Approved — fits within team budget.',
  },
  {
    id: 'nx-req-3',
    toolName: 'Pitch',
    category: 'Design',
    useCase: 'Sales deck creation — faster than Google Slides',
    estimatedMonthlyCost: 200,
    urgency: 'medium',
    requester: 'Marcus Johnson',
    status: 'denied',
    submittedAt: '2026-02-10T11:00:00Z',
    reviewedAt: '2026-02-12T16:00:00Z',
    reviewerComment: 'We already have Figma for presentations. Consolidate there.',
  },
  {
    id: 'nx-req-4',
    toolName: 'Calendly',
    category: 'Other',
    useCase: 'External meeting scheduling for sales team',
    estimatedMonthlyCost: 120,
    urgency: 'medium',
    requester: 'Jamie Torres',
    status: 'pending',
    submittedAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'nx-req-5',
    toolName: 'Snyk',
    category: 'Security',
    useCase: 'Automated dependency vulnerability scanning for CI/CD pipeline',
    estimatedMonthlyCost: 500,
    urgency: 'high',
    requester: 'Wei Zhang',
    status: 'pending',
    submittedAt: '2026-03-04T13:00:00Z',
  },
  {
    id: 'nx-req-6',
    toolName: 'Lattice',
    category: 'HR',
    useCase: 'Performance review platform for 125-person org — Workday lacks the depth',
    estimatedMonthlyCost: 750,
    urgency: 'medium',
    requester: 'Dana Kim',
    status: 'denied',
    submittedAt: '2026-01-20T09:00:00Z',
    reviewedAt: '2026-01-25T11:00:00Z',
    reviewerComment: 'Budget freeze on HR tools until Q3. Revisit after Workday contract review.',
  },
  {
    id: 'nx-req-7',
    toolName: 'Tableau',
    category: 'Analytics',
    useCase: 'Executive BI dashboards — Datadog is ops-only, leadership needs business KPI visibility',
    estimatedMonthlyCost: 1200,
    urgency: 'high',
    requester: 'Priya Mehta',
    status: 'pending',
    submittedAt: '2026-03-06T10:00:00Z',
  },
  {
    id: 'nx-req-8',
    toolName: 'Figma Enterprise',
    category: 'Design',
    useCase: 'Upgrade current Figma plan to Enterprise for SSO, advanced admin, and audit logs',
    estimatedMonthlyCost: 900,
    urgency: 'medium',
    requester: 'Jordan Lee',
    status: 'approved',
    submittedAt: '2026-01-10T09:00:00Z',
    reviewedAt: '2026-01-13T14:00:00Z',
    reviewerComment: 'Approved — SSO requirement for SOC2 compliance. Coordinate with IT.',
  },
  {
    id: 'nx-req-9',
    toolName: 'Outreach',
    category: 'CRM',
    useCase: 'Sales engagement platform for SDR team — automate outbound sequences',
    estimatedMonthlyCost: 1500,
    urgency: 'high',
    requester: 'Carlos Rivera',
    status: 'denied',
    submittedAt: '2026-01-05T11:00:00Z',
    reviewedAt: '2026-01-08T09:00:00Z',
    reviewerComment: 'Too much CRM overlap. Resolve Salesforce/HubSpot/Intercom consolidation first before adding another tool.',
  },
  {
    id: 'nx-req-10',
    toolName: 'Mural',
    category: 'Design',
    useCase: 'Digital whiteboarding for distributed design sprints',
    estimatedMonthlyCost: 180,
    urgency: 'low',
    requester: 'Sophie Larsen',
    status: 'denied',
    submittedAt: '2025-12-15T10:00:00Z',
    reviewedAt: '2025-12-18T11:00:00Z',
    reviewerComment: 'Miro already covers this. Request declined — use existing Miro licenses.',
  },
  {
    id: 'nx-req-11',
    toolName: 'BambooHR',
    category: 'HR',
    useCase: 'Employee self-service portal and PTO tracking — simpler than Workday for day-to-day',
    estimatedMonthlyCost: 625,
    urgency: 'low',
    requester: 'Dana Kim',
    status: 'approved',
    submittedAt: '2025-11-20T09:00:00Z',
    reviewedAt: '2025-11-24T14:00:00Z',
    reviewerComment: 'Approved for the HR team only (10 seats). Monitor for overlap with Workday.',
  },
];

// ─── Orbit Analytics ─────────────────────────────────────────────────────────
// 45-person data startup. Overlaps: CRM, Analytics (3-way), Dev, Design

const orbitTools: Tool[] = [
  { id: 'ob-1',  name: 'Slack',       category: 'Communication',      monthlyCost: 450,   seats: 45,  owner: 'IT',          renewalDate: '2026-03-12', status: 'active' },
  { id: 'ob-2',  name: 'Google Meet', category: 'Communication',      monthlyCost: 270,   seats: 45,  owner: 'IT',          renewalDate: '2026-08-01', status: 'active' },
  { id: 'ob-3',  name: 'Loom',        category: 'Communication',      monthlyCost: 135,   seats: 20,  owner: 'Product',     renewalDate: '2026-06-10', status: 'active' },
  { id: 'ob-4',  name: 'Linear',      category: 'Project Management', monthlyCost: 360,   seats: 30,  owner: 'Engineering', renewalDate: '2026-09-15', status: 'active' },
  { id: 'ob-5',  name: 'Asana',       category: 'Project Management', monthlyCost: 290,   seats: 20,  owner: 'Ops',         renewalDate: '2026-04-22', status: 'review' },
  { id: 'ob-6',  name: 'Pipedrive',   category: 'CRM',                monthlyCost: 600,   seats: 12,  owner: 'Sales',       renewalDate: '2026-03-25', status: 'active' },
  { id: 'ob-7',  name: 'HubSpot',     category: 'CRM',                monthlyCost: 890,   seats: 10,  owner: 'Marketing',   renewalDate: '2026-05-10', status: 'review' },
  { id: 'ob-8',  name: 'Intercom',    category: 'CRM',                monthlyCost: 540,   seats: 8,   owner: 'Support',     renewalDate: '2026-07-01', status: 'review' },
  { id: 'ob-9',  name: 'Figma',       category: 'Design',             monthlyCost: 180,   seats: 6,   owner: 'Design',      renewalDate: '2026-11-20', status: 'active' },
  { id: 'ob-10', name: 'Canva',       category: 'Design',             monthlyCost: 120,   seats: 15,  owner: 'Marketing',   renewalDate: '2026-05-05', status: 'active' },
  { id: 'ob-11', name: 'Rippling',    category: 'HR',                 monthlyCost: 720,   seats: 45,  owner: 'HR',          renewalDate: '2026-12-01', status: 'active' },
  { id: 'ob-12', name: 'Notion',      category: 'Docs',               monthlyCost: 360,   seats: 45,  owner: 'Product',     renewalDate: '2026-07-30', status: 'active' },
  { id: 'ob-13', name: 'Mixpanel',    category: 'Analytics',          monthlyCost: 1200,  seats: 20,  owner: 'Product',     renewalDate: '2026-10-05', status: 'active' },
  { id: 'ob-14', name: 'Amplitude',   category: 'Analytics',          monthlyCost: 950,   seats: 18,  owner: 'Data',        renewalDate: '2026-04-18', status: 'review' },
  { id: 'ob-15', name: 'Looker',      category: 'Analytics',          monthlyCost: 1800,  seats: 15,  owner: 'Data',        renewalDate: '2026-08-20', status: 'review' },
  { id: 'ob-16', name: 'GitHub',      category: 'Development',        monthlyCost: 540,   seats: 30,  owner: 'Engineering', renewalDate: '2026-06-01', status: 'active' },
  { id: 'ob-17', name: 'Vercel',      category: 'Development',        monthlyCost: 400,   seats: 10,  owner: 'Engineering', renewalDate: '2026-09-01', status: 'active' },
  { id: 'ob-18', name: 'dbt Cloud',   category: 'Development',        monthlyCost: 600,   seats: 8,   owner: 'Data',        renewalDate: '2026-11-15', status: 'active' },
  { id: 'ob-19', name: 'Snowflake',   category: 'Analytics',          monthlyCost: 3200,  seats: 12,  owner: 'Data',        renewalDate: '2026-06-30', status: 'active' },
  { id: 'ob-20', name: '1Password',   category: 'Security',           monthlyCost: 135,   seats: 45,  owner: 'IT',          renewalDate: '2026-08-20', status: 'active' },
  { id: 'ob-21', name: 'Retool',      category: 'Development',        monthlyCost: 600,   seats: 12,  owner: 'Engineering', renewalDate: '2026-10-01', status: 'active' },
  { id: 'ob-22', name: 'Sentry',      category: 'Analytics',          monthlyCost: 380,   seats: 20,  owner: 'Engineering', renewalDate: '2026-07-15', status: 'active' },
];

const orbitRequests: ApprovalRequest[] = [
  {
    id: 'ob-req-1',
    toolName: 'Tableau',
    category: 'Analytics',
    useCase: 'Executive dashboards for board reporting — Mixpanel lacks the visualization depth',
    estimatedMonthlyCost: 1400,
    urgency: 'high',
    requester: 'Priya Nair',
    status: 'pending',
    submittedAt: '2026-03-02T09:00:00Z',
  },
  {
    id: 'ob-req-2',
    toolName: 'Intercom',
    category: 'CRM',
    useCase: 'In-app customer support chat for SaaS product',
    estimatedMonthlyCost: 500,
    urgency: 'medium',
    requester: 'Tom Okafor',
    status: 'approved',
    submittedAt: '2026-02-20T11:00:00Z',
    reviewedAt: '2026-02-22T14:00:00Z',
    reviewerComment: 'Approved. Review CRM overlap in Q3.',
  },
  {
    id: 'ob-req-3',
    toolName: 'Vercel Pro',
    category: 'Development',
    useCase: 'Production deployment for customer-facing dashboards',
    estimatedMonthlyCost: 200,
    urgency: 'high',
    requester: 'Dani Park',
    status: 'pending',
    submittedAt: '2026-03-04T16:00:00Z',
  },
  {
    id: 'ob-req-4',
    toolName: 'Lattice',
    category: 'HR',
    useCase: 'Performance review cycles as team grows past 40',
    estimatedMonthlyCost: 450,
    urgency: 'low',
    requester: 'Meera Singh',
    status: 'denied',
    submittedAt: '2026-02-08T10:00:00Z',
    reviewedAt: '2026-02-10T09:00:00Z',
    reviewerComment: 'Not in budget for H1. Revisit in Q3 with HR roadmap.',
  },
  {
    id: 'ob-req-5',
    toolName: 'Okta',
    category: 'Security',
    useCase: 'SSO and MFA for all 45 employees — critical as we hit SOC2',
    estimatedMonthlyCost: 675,
    urgency: 'high',
    requester: 'Raj Kumar',
    status: 'pending',
    submittedAt: '2026-03-05T10:00:00Z',
  },
  {
    id: 'ob-req-6',
    toolName: 'Miro',
    category: 'Design',
    useCase: 'Async design collaboration across remote team',
    estimatedMonthlyCost: 135,
    urgency: 'low',
    requester: 'Elena Russo',
    status: 'denied',
    submittedAt: '2026-02-01T09:00:00Z',
    reviewedAt: '2026-02-03T11:00:00Z',
    reviewerComment: 'Figma covers this. Request Figma team seats expansion instead.',
  },
  {
    id: 'ob-req-7',
    toolName: 'dbt Cloud Team',
    category: 'Development',
    useCase: 'Upgrade from dbt Cloud Developer to Team tier for scheduled jobs and metadata API',
    estimatedMonthlyCost: 300,
    urgency: 'high',
    requester: 'Amir Hassan',
    status: 'approved',
    submittedAt: '2026-01-12T10:00:00Z',
    reviewedAt: '2026-01-14T09:00:00Z',
    reviewerComment: 'Approved — critical for data pipeline reliability. Expense under engineering infrastructure.',
  },
  {
    id: 'ob-req-8',
    toolName: 'PostHog',
    category: 'Analytics',
    useCase: 'Product analytics with session replay — overlaps with Mixpanel but open-source and cheaper',
    estimatedMonthlyCost: 400,
    urgency: 'medium',
    requester: 'Sophie Chen',
    status: 'denied',
    submittedAt: '2026-01-25T14:00:00Z',
    reviewedAt: '2026-01-28T11:00:00Z',
    reviewerComment: 'We already have Mixpanel, Amplitude, and Looker. No more analytics tools until we consolidate. Denied.',
  },
  {
    id: 'ob-req-9',
    toolName: 'Notion AI',
    category: 'Docs',
    useCase: 'AI writing assistance add-on for existing Notion workspace',
    estimatedMonthlyCost: 180,
    urgency: 'low',
    requester: 'Meera Singh',
    status: 'approved',
    submittedAt: '2025-12-10T09:00:00Z',
    reviewedAt: '2025-12-12T14:00:00Z',
    reviewerComment: 'Low cost, high value for documentation quality. Approved.',
  },
  {
    id: 'ob-req-10',
    toolName: 'PagerDuty',
    category: 'Analytics',
    useCase: 'On-call incident management — Snowflake pipeline failures need alerting beyond Slack',
    estimatedMonthlyCost: 450,
    urgency: 'high',
    requester: 'Raj Kumar',
    status: 'pending',
    submittedAt: '2026-03-06T09:00:00Z',
  },
  {
    id: 'ob-req-11',
    toolName: 'HubSpot Marketing Hub',
    category: 'CRM',
    useCase: 'Upgrade HubSpot to Marketing Hub Pro for email automation and lead scoring',
    estimatedMonthlyCost: 800,
    urgency: 'medium',
    requester: 'Tom Okafor',
    status: 'pending',
    submittedAt: '2026-03-05T11:00:00Z',
  },
];

// ─── Cascade Labs ─────────────────────────────────────────────────────────────
// 80-person dev shop. Overlaps: PM, Docs, Dev (3-way), Analytics (3-way), CRM, Security

const cascadeTools: Tool[] = [
  { id: 'ca-1',  name: 'Slack',             category: 'Communication',      monthlyCost: 800,   seats: 80,  owner: 'IT',          renewalDate: '2026-05-01', status: 'active' },
  { id: 'ca-2',  name: 'Zoom',              category: 'Communication',      monthlyCost: 480,   seats: 60,  owner: 'IT',          renewalDate: '2026-03-10', status: 'active' },
  { id: 'ca-3',  name: 'Jira',              category: 'Project Management', monthlyCost: 1040,  seats: 80,  owner: 'Engineering', renewalDate: '2026-03-22', status: 'active' },
  { id: 'ca-4',  name: 'Asana',             category: 'Project Management', monthlyCost: 640,   seats: 40,  owner: 'Ops',         renewalDate: '2026-06-15', status: 'review' },
  { id: 'ca-5',  name: 'Linear',            category: 'Project Management', monthlyCost: 480,   seats: 30,  owner: 'Engineering', renewalDate: '2026-09-01', status: 'review' },
  { id: 'ca-6',  name: 'Salesforce',        category: 'CRM',                monthlyCost: 2400,  seats: 20,  owner: 'Sales',       renewalDate: '2026-08-01', status: 'active' },
  { id: 'ca-7',  name: 'HubSpot',           category: 'CRM',                monthlyCost: 1200,  seats: 20,  owner: 'Marketing',   renewalDate: '2026-09-30', status: 'review' },
  { id: 'ca-8',  name: 'Figma',             category: 'Design',             monthlyCost: 320,   seats: 12,  owner: 'Design',      renewalDate: '2026-11-01', status: 'active' },
  { id: 'ca-9',  name: 'Miro',              category: 'Design',             monthlyCost: 240,   seats: 25,  owner: 'Product',     renewalDate: '2026-06-20', status: 'active' },
  { id: 'ca-10', name: 'Workday',           category: 'HR',                 monthlyCost: 1920,  seats: 80,  owner: 'HR',          renewalDate: '2027-01-01', status: 'active' },
  { id: 'ca-11', name: 'Greenhouse',        category: 'HR',                 monthlyCost: 640,   seats: 15,  owner: 'HR',          renewalDate: '2026-07-10', status: 'active' },
  { id: 'ca-12', name: 'Confluence',        category: 'Docs',               monthlyCost: 640,   seats: 80,  owner: 'Engineering', renewalDate: '2026-08-10', status: 'active' },
  { id: 'ca-13', name: 'Notion',            category: 'Docs',               monthlyCost: 480,   seats: 60,  owner: 'Product',     renewalDate: '2026-04-28', status: 'review' },
  { id: 'ca-14', name: 'GitHub',            category: 'Development',        monthlyCost: 800,   seats: 75,  owner: 'Engineering', renewalDate: '2026-03-31', status: 'active' },
  { id: 'ca-15', name: 'GitLab',            category: 'Development',        monthlyCost: 600,   seats: 30,  owner: 'Engineering', renewalDate: '2026-07-01', status: 'review' },
  { id: 'ca-16', name: 'CircleCI',          category: 'Development',        monthlyCost: 480,   seats: 25,  owner: 'DevOps',      renewalDate: '2026-05-20', status: 'active' },
  { id: 'ca-17', name: 'Datadog',           category: 'Analytics',          monthlyCost: 1800,  seats: 25,  owner: 'DevOps',      renewalDate: '2026-10-15', status: 'active' },
  { id: 'ca-18', name: 'Sentry',            category: 'Analytics',          monthlyCost: 420,   seats: 40,  owner: 'Engineering', renewalDate: '2026-12-20', status: 'active' },
  { id: 'ca-19', name: 'New Relic',         category: 'Analytics',          monthlyCost: 1200,  seats: 20,  owner: 'DevOps',      renewalDate: '2026-06-01', status: 'review' },
  { id: 'ca-20', name: 'PagerDuty',         category: 'Analytics',          monthlyCost: 560,   seats: 20,  owner: 'DevOps',      renewalDate: '2026-09-10', status: 'active' },
  { id: 'ca-21', name: '1Password',         category: 'Security',           monthlyCost: 240,   seats: 80,  owner: 'IT',          renewalDate: '2026-05-15', status: 'active' },
  { id: 'ca-22', name: 'Okta',              category: 'Security',           monthlyCost: 1200,  seats: 80,  owner: 'IT',          renewalDate: '2026-04-15', status: 'active' },
  { id: 'ca-23', name: 'Snyk',              category: 'Security',           monthlyCost: 640,   seats: 40,  owner: 'Engineering', renewalDate: '2026-11-30', status: 'active' },
  { id: 'ca-24', name: 'Terraform Cloud',   category: 'Development',        monthlyCost: 400,   seats: 15,  owner: 'DevOps',      renewalDate: '2026-08-01', status: 'active' },
  { id: 'ca-25', name: 'DocuSign',          category: 'Other',              monthlyCost: 200,   seats: 8,   owner: 'Legal',       renewalDate: '2026-10-01', status: 'active' },
];

const cascadeRequests: ApprovalRequest[] = [
  {
    id: 'ca-req-1',
    toolName: 'Linear',
    category: 'Project Management',
    useCase: 'Replace Asana for dev team — better GitHub integration than Jira',
    estimatedMonthlyCost: 560,
    urgency: 'medium',
    requester: 'Raj Patel',
    status: 'pending',
    submittedAt: '2026-03-03T10:00:00Z',
  },
  {
    id: 'ca-req-2',
    toolName: 'Doppler',
    category: 'Security',
    useCase: 'Secrets management across 12 microservices — replacing manual env file rotation',
    estimatedMonthlyCost: 300,
    urgency: 'high',
    requester: 'Elena Vasquez',
    status: 'approved',
    submittedAt: '2026-02-25T09:00:00Z',
    reviewedAt: '2026-02-26T11:00:00Z',
    reviewerComment: 'Critical for compliance. Approved immediately.',
  },
  {
    id: 'ca-req-3',
    toolName: 'Retool',
    category: 'Development',
    useCase: 'Internal admin dashboards for client delivery team',
    estimatedMonthlyCost: 800,
    urgency: 'medium',
    requester: 'Sam Okonkwo',
    status: 'pending',
    submittedAt: '2026-03-05T14:00:00Z',
  },
  {
    id: 'ca-req-4',
    toolName: 'Loom',
    category: 'Communication',
    useCase: 'Async video updates for remote client teams',
    estimatedMonthlyCost: 160,
    urgency: 'low',
    requester: 'Fatima Al-Hassan',
    status: 'denied',
    submittedAt: '2026-02-12T08:00:00Z',
    reviewedAt: '2026-02-14T10:00:00Z',
    reviewerComment: 'Zoom recordings cover this use case adequately.',
  },
  {
    id: 'ca-req-5',
    toolName: 'Crowdstrike',
    category: 'Security',
    useCase: 'Endpoint detection and response for 80 developer machines — SOC2 requirement',
    estimatedMonthlyCost: 1600,
    urgency: 'high',
    requester: 'Marcus Webb',
    status: 'pending',
    submittedAt: '2026-03-06T09:00:00Z',
  },
  {
    id: 'ca-req-6',
    toolName: 'Tableau',
    category: 'Analytics',
    useCase: 'Client-facing analytics reports — Datadog is ops-focused, need a BI tool',
    estimatedMonthlyCost: 1000,
    urgency: 'medium',
    requester: 'Nina Johansson',
    status: 'pending',
    submittedAt: '2026-03-01T14:00:00Z',
  },
  {
    id: 'ca-req-7',
    toolName: 'Vercel Pro',
    category: 'Development',
    useCase: 'Deploy customer preview environments — CircleCI handles CI but we need Vercel for previews',
    estimatedMonthlyCost: 400,
    urgency: 'high',
    requester: 'Sam Okonkwo',
    status: 'approved',
    submittedAt: '2026-01-08T09:00:00Z',
    reviewedAt: '2026-01-09T14:00:00Z',
    reviewerComment: 'Approved. Existing GitHub/GitLab/CircleCI stack can co-exist with Vercel for deployment previews.',
  },
  {
    id: 'ca-req-8',
    toolName: 'Shortcut',
    category: 'Project Management',
    useCase: 'Replace Asana for the product team — better story mapping and sprint planning',
    estimatedMonthlyCost: 320,
    urgency: 'medium',
    requester: 'Raj Patel',
    status: 'denied',
    submittedAt: '2026-01-15T10:00:00Z',
    reviewedAt: '2026-01-20T09:00:00Z',
    reviewerComment: 'We already have Jira, Asana, and Linear in PM. Consolidate first. Request denied.',
  },
  {
    id: 'ca-req-9',
    toolName: 'Datadog APM',
    category: 'Analytics',
    useCase: 'Add APM module to existing Datadog subscription for distributed tracing across microservices',
    estimatedMonthlyCost: 600,
    urgency: 'high',
    requester: 'Marcus Webb',
    status: 'approved',
    submittedAt: '2025-12-05T10:00:00Z',
    reviewedAt: '2025-12-08T14:00:00Z',
    reviewerComment: 'Approved as add-on to existing Datadog. Negotiate bundle pricing at next renewal.',
  },
  {
    id: 'ca-req-10',
    toolName: 'Figma Enterprise',
    category: 'Design',
    useCase: 'Enterprise plan for SSO, audit logs, and centralized billing across all design teams',
    estimatedMonthlyCost: 640,
    urgency: 'medium',
    requester: 'Amara Nwosu',
    status: 'pending',
    submittedAt: '2026-03-04T09:00:00Z',
  },
  {
    id: 'ca-req-11',
    toolName: 'Spacelift',
    category: 'Development',
    useCase: 'GitOps for Terraform — policy-as-code enforcement across all cloud infrastructure',
    estimatedMonthlyCost: 500,
    urgency: 'medium',
    requester: 'Elena Vasquez',
    status: 'denied',
    submittedAt: '2025-11-10T10:00:00Z',
    reviewedAt: '2025-11-14T11:00:00Z',
    reviewerComment: 'Terraform Cloud already provides remote state and run environments. Evaluate after Q1 infra review.',
  },
];

// ─── Lookup helpers ───────────────────────────────────────────────────────────

const seedToolsMap: Record<string, Tool[]> = {
  nexus: nexusTools,
  orbit: orbitTools,
  cascade: cascadeTools,
};

const seedRequestsMap: Record<string, ApprovalRequest[]> = {
  nexus: nexusRequests,
  orbit: orbitRequests,
  cascade: cascadeRequests,
};

export function getSeedTools(clientId: string): Tool[] {
  return seedToolsMap[clientId] ?? [];
}

export function getSeedRequests(clientId: string): ApprovalRequest[] {
  return seedRequestsMap[clientId] ?? [];
}
