import { Tool, ApprovalRequest, Client } from './types';

// ─── Client registry ──────────────────────────────────────────────────────────

export const clients: Client[] = [
  { id: 'nexus', name: 'Nexus Systems', industry: 'B2B SaaS', employees: 125 },
  { id: 'orbit', name: 'Orbit Analytics', industry: 'Data & AI', employees: 45 },
  { id: 'cascade', name: 'Cascade Labs', industry: 'Software Dev', employees: 80 },
];

// ─── Nexus Systems ────────────────────────────────────────────────────────────
// 125-person B2B SaaS company. Overlaps: PM (Asana/Monday), CRM (Salesforce/HubSpot), Docs (Notion/Confluence)

const nexusTools: Tool[] = [
  {
    id: 'nx-1',
    name: 'Slack',
    category: 'Communication',
    monthlyCost: 1250,
    seats: 125,
    owner: 'IT',
    renewalDate: '2026-03-15',
    status: 'active',
  },
  {
    id: 'nx-2',
    name: 'Zoom',
    category: 'Communication',
    monthlyCost: 800,
    seats: 100,
    owner: 'IT',
    renewalDate: '2026-03-28',
    status: 'active',
  },
  {
    id: 'nx-3',
    name: 'Loom',
    category: 'Communication',
    monthlyCost: 200,
    seats: 40,
    owner: 'Marketing',
    renewalDate: '2026-05-20',
    status: 'active',
  },
  {
    id: 'nx-4',
    name: 'Asana',
    category: 'Project Management',
    monthlyCost: 1500,
    seats: 80,
    owner: 'Ops',
    renewalDate: '2026-06-10',
    status: 'active',
  },
  {
    id: 'nx-5',
    name: 'Monday.com',
    category: 'Project Management',
    monthlyCost: 1100,
    seats: 60,
    owner: 'Engineering',
    renewalDate: '2026-07-22',
    status: 'review',
  },
  {
    id: 'nx-6',
    name: 'Salesforce',
    category: 'CRM',
    monthlyCost: 4500,
    seats: 50,
    owner: 'Sales',
    renewalDate: '2026-11-30',
    status: 'active',
  },
  {
    id: 'nx-7',
    name: 'HubSpot',
    category: 'CRM',
    monthlyCost: 1800,
    seats: 30,
    owner: 'Marketing',
    renewalDate: '2026-04-02',
    status: 'review',
  },
  {
    id: 'nx-8',
    name: 'Figma',
    category: 'Design',
    monthlyCost: 450,
    seats: 15,
    owner: 'Design',
    renewalDate: '2026-10-12',
    status: 'active',
  },
  {
    id: 'nx-9',
    name: 'Miro',
    category: 'Design',
    monthlyCost: 320,
    seats: 40,
    owner: 'Product',
    renewalDate: '2026-12-01',
    status: 'active',
  },
  {
    id: 'nx-10',
    name: 'Workday',
    category: 'HR',
    monthlyCost: 3200,
    seats: 125,
    owner: 'HR',
    renewalDate: '2027-01-15',
    status: 'active',
  },
  {
    id: 'nx-11',
    name: 'Greenhouse',
    category: 'HR',
    monthlyCost: 950,
    seats: 20,
    owner: 'HR',
    renewalDate: '2026-09-01',
    status: 'active',
  },
  {
    id: 'nx-12',
    name: 'Notion',
    category: 'Docs',
    monthlyCost: 600,
    seats: 120,
    owner: 'Product',
    renewalDate: '2026-06-28',
    status: 'active',
  },
  {
    id: 'nx-13',
    name: 'Confluence',
    category: 'Docs',
    monthlyCost: 750,
    seats: 90,
    owner: 'Engineering',
    renewalDate: '2026-07-15',
    status: 'review',
  },
  {
    id: 'nx-14',
    name: 'DocuSign',
    category: 'Other',
    monthlyCost: 300,
    seats: 10,
    owner: 'Legal',
    renewalDate: '2026-10-30',
    status: 'active',
  },
  {
    id: 'nx-15',
    name: '1Password',
    category: 'Security',
    monthlyCost: 375,
    seats: 125,
    owner: 'IT',
    renewalDate: '2026-04-01',
    status: 'active',
  },
];

const nexusRequests: ApprovalRequest[] = [
  {
    id: 'nx-req-1',
    toolName: 'Linear',
    category: 'Project Management',
    useCase: 'Engineering issue tracking — cleaner than Asana for dev workflows',
    estimatedMonthlyCost: 400,
    urgency: 'high',
    requester: 'Alex Chen',
    status: 'pending',
    submittedAt: '2026-02-28T10:00:00Z',
  },
  {
    id: 'nx-req-2',
    toolName: 'Grammarly Business',
    category: 'Other',
    useCase: 'Writing quality improvement for customer-facing content',
    estimatedMonthlyCost: 150,
    urgency: 'low',
    requester: 'Sarah Park',
    status: 'approved',
    submittedAt: '2026-02-15T14:30:00Z',
    reviewedAt: '2026-02-17T09:00:00Z',
    reviewerComment: 'Approved — fits within team budget.',
  },
  {
    id: 'nx-req-3',
    toolName: 'Pitch',
    category: 'Design',
    useCase: 'Sales deck creation — faster than Google Slides',
    estimatedMonthlyCost: 200,
    urgency: 'medium',
    requester: 'Marcus Johnson',
    status: 'denied',
    submittedAt: '2026-02-10T11:00:00Z',
    reviewedAt: '2026-02-12T16:00:00Z',
    reviewerComment: 'We already have Figma for presentations. Consolidate there.',
  },
  {
    id: 'nx-req-4',
    toolName: 'Calendly',
    category: 'Other',
    useCase: 'External meeting scheduling for sales team',
    estimatedMonthlyCost: 120,
    urgency: 'medium',
    requester: 'Jamie Torres',
    status: 'pending',
    submittedAt: '2026-03-01T08:00:00Z',
  },
];

// ─── Orbit Analytics ─────────────────────────────────────────────────────────
// 45-person data startup. Overlaps: CRM (Pipedrive/HubSpot), Analytics (Mixpanel/Amplitude)

const orbitTools: Tool[] = [
  {
    id: 'ob-1',
    name: 'Slack',
    category: 'Communication',
    monthlyCost: 450,
    seats: 45,
    owner: 'IT',
    renewalDate: '2026-03-12',
    status: 'active',
  },
  {
    id: 'ob-2',
    name: 'Google Meet',
    category: 'Communication',
    monthlyCost: 270,
    seats: 45,
    owner: 'IT',
    renewalDate: '2026-08-01',
    status: 'active',
  },
  {
    id: 'ob-3',
    name: 'Linear',
    category: 'Project Management',
    monthlyCost: 360,
    seats: 30,
    owner: 'Engineering',
    renewalDate: '2026-09-15',
    status: 'active',
  },
  {
    id: 'ob-4',
    name: 'Pipedrive',
    category: 'CRM',
    monthlyCost: 600,
    seats: 12,
    owner: 'Sales',
    renewalDate: '2026-03-25',
    status: 'active',
  },
  {
    id: 'ob-5',
    name: 'HubSpot',
    category: 'CRM',
    monthlyCost: 890,
    seats: 10,
    owner: 'Marketing',
    renewalDate: '2026-05-10',
    status: 'review',
  },
  {
    id: 'ob-6',
    name: 'Figma',
    category: 'Design',
    monthlyCost: 180,
    seats: 6,
    owner: 'Design',
    renewalDate: '2026-11-20',
    status: 'active',
  },
  {
    id: 'ob-7',
    name: 'Rippling',
    category: 'HR',
    monthlyCost: 720,
    seats: 45,
    owner: 'HR',
    renewalDate: '2026-12-01',
    status: 'active',
  },
  {
    id: 'ob-8',
    name: 'Notion',
    category: 'Docs',
    monthlyCost: 360,
    seats: 45,
    owner: 'Product',
    renewalDate: '2026-07-30',
    status: 'active',
  },
  {
    id: 'ob-9',
    name: 'Mixpanel',
    category: 'Analytics',
    monthlyCost: 1200,
    seats: 20,
    owner: 'Product',
    renewalDate: '2026-10-05',
    status: 'active',
  },
  {
    id: 'ob-10',
    name: 'Amplitude',
    category: 'Analytics',
    monthlyCost: 950,
    seats: 18,
    owner: 'Data',
    renewalDate: '2026-04-18',
    status: 'review',
  },
  {
    id: 'ob-11',
    name: 'GitHub',
    category: 'Development',
    monthlyCost: 540,
    seats: 30,
    owner: 'Engineering',
    renewalDate: '2026-06-01',
    status: 'active',
  },
  {
    id: 'ob-12',
    name: '1Password',
    category: 'Security',
    monthlyCost: 135,
    seats: 45,
    owner: 'IT',
    renewalDate: '2026-08-20',
    status: 'active',
  },
];

const orbitRequests: ApprovalRequest[] = [
  {
    id: 'ob-req-1',
    toolName: 'Tableau',
    category: 'Analytics',
    useCase: 'Executive dashboards for board reporting — Mixpanel lacks the visualization depth',
    estimatedMonthlyCost: 1400,
    urgency: 'high',
    requester: 'Priya Nair',
    status: 'pending',
    submittedAt: '2026-03-02T09:00:00Z',
  },
  {
    id: 'ob-req-2',
    toolName: 'Intercom',
    category: 'CRM',
    useCase: 'In-app customer support chat for SaaS product',
    estimatedMonthlyCost: 500,
    urgency: 'medium',
    requester: 'Tom Okafor',
    status: 'approved',
    submittedAt: '2026-02-20T11:00:00Z',
    reviewedAt: '2026-02-22T14:00:00Z',
    reviewerComment: 'Approved. Review CRM overlap in Q3.',
  },
  {
    id: 'ob-req-3',
    toolName: 'Vercel Pro',
    category: 'Development',
    useCase: 'Production deployment for customer-facing dashboards',
    estimatedMonthlyCost: 200,
    urgency: 'high',
    requester: 'Dani Park',
    status: 'pending',
    submittedAt: '2026-03-04T16:00:00Z',
  },
  {
    id: 'ob-req-4',
    toolName: 'Lattice',
    category: 'HR',
    useCase: 'Performance review cycles as team grows past 40',
    estimatedMonthlyCost: 450,
    urgency: 'low',
    requester: 'Meera Singh',
    status: 'denied',
    submittedAt: '2026-02-08T10:00:00Z',
    reviewedAt: '2026-02-10T09:00:00Z',
    reviewerComment: 'Not in budget for H1. Revisit in Q3 with HR roadmap.',
  },
];

// ─── Cascade Labs ─────────────────────────────────────────────────────────────
// 80-person dev shop. Overlaps: PM (Jira/Asana), Docs (Confluence/Notion), Dev (GitHub/GitLab)

const cascadeTools: Tool[] = [
  {
    id: 'ca-1',
    name: 'Slack',
    category: 'Communication',
    monthlyCost: 800,
    seats: 80,
    owner: 'IT',
    renewalDate: '2026-05-01',
    status: 'active',
  },
  {
    id: 'ca-2',
    name: 'Zoom',
    category: 'Communication',
    monthlyCost: 480,
    seats: 60,
    owner: 'IT',
    renewalDate: '2026-03-10',
    status: 'active',
  },
  {
    id: 'ca-3',
    name: 'Jira',
    category: 'Project Management',
    monthlyCost: 1040,
    seats: 80,
    owner: 'Engineering',
    renewalDate: '2026-03-22',
    status: 'active',
  },
  {
    id: 'ca-4',
    name: 'Asana',
    category: 'Project Management',
    monthlyCost: 640,
    seats: 40,
    owner: 'Ops',
    renewalDate: '2026-06-15',
    status: 'review',
  },
  {
    id: 'ca-5',
    name: 'HubSpot',
    category: 'CRM',
    monthlyCost: 1200,
    seats: 20,
    owner: 'Sales',
    renewalDate: '2026-09-30',
    status: 'active',
  },
  {
    id: 'ca-6',
    name: 'Figma',
    category: 'Design',
    monthlyCost: 320,
    seats: 12,
    owner: 'Design',
    renewalDate: '2026-11-01',
    status: 'active',
  },
  {
    id: 'ca-7',
    name: 'Workday',
    category: 'HR',
    monthlyCost: 1920,
    seats: 80,
    owner: 'HR',
    renewalDate: '2027-01-01',
    status: 'active',
  },
  {
    id: 'ca-8',
    name: 'Confluence',
    category: 'Docs',
    monthlyCost: 640,
    seats: 80,
    owner: 'Engineering',
    renewalDate: '2026-08-10',
    status: 'active',
  },
  {
    id: 'ca-9',
    name: 'Notion',
    category: 'Docs',
    monthlyCost: 480,
    seats: 60,
    owner: 'Product',
    renewalDate: '2026-04-28',
    status: 'review',
  },
  {
    id: 'ca-10',
    name: 'GitHub',
    category: 'Development',
    monthlyCost: 800,
    seats: 75,
    owner: 'Engineering',
    renewalDate: '2026-03-31',
    status: 'active',
  },
  {
    id: 'ca-11',
    name: 'GitLab',
    category: 'Development',
    monthlyCost: 600,
    seats: 30,
    owner: 'Engineering',
    renewalDate: '2026-07-01',
    status: 'review',
  },
  {
    id: 'ca-12',
    name: 'Datadog',
    category: 'Analytics',
    monthlyCost: 1800,
    seats: 25,
    owner: 'DevOps',
    renewalDate: '2026-10-15',
    status: 'active',
  },
  {
    id: 'ca-13',
    name: 'Sentry',
    category: 'Analytics',
    monthlyCost: 420,
    seats: 40,
    owner: 'Engineering',
    renewalDate: '2026-12-20',
    status: 'active',
  },
  {
    id: 'ca-14',
    name: '1Password',
    category: 'Security',
    monthlyCost: 240,
    seats: 80,
    owner: 'IT',
    renewalDate: '2026-05-15',
    status: 'active',
  },
];

const cascadeRequests: ApprovalRequest[] = [
  {
    id: 'ca-req-1',
    toolName: 'Linear',
    category: 'Project Management',
    useCase: 'Replace Asana for dev team — better GitHub integration than Jira',
    estimatedMonthlyCost: 560,
    urgency: 'medium',
    requester: 'Raj Patel',
    status: 'pending',
    submittedAt: '2026-03-03T10:00:00Z',
  },
  {
    id: 'ca-req-2',
    toolName: 'Doppler',
    category: 'Security',
    useCase: 'Secrets management across 12 microservices — replacing manual env file rotation',
    estimatedMonthlyCost: 300,
    urgency: 'high',
    requester: 'Elena Vasquez',
    status: 'approved',
    submittedAt: '2026-02-25T09:00:00Z',
    reviewedAt: '2026-02-26T11:00:00Z',
    reviewerComment: 'Critical for compliance. Approved immediately.',
  },
  {
    id: 'ca-req-3',
    toolName: 'Retool',
    category: 'Development',
    useCase: 'Internal admin dashboards for client delivery team',
    estimatedMonthlyCost: 800,
    urgency: 'medium',
    requester: 'Sam Okonkwo',
    status: 'pending',
    submittedAt: '2026-03-05T14:00:00Z',
  },
  {
    id: 'ca-req-4',
    toolName: 'Loom',
    category: 'Communication',
    useCase: 'Async video updates for remote client teams',
    estimatedMonthlyCost: 160,
    urgency: 'low',
    requester: 'Fatima Al-Hassan',
    status: 'denied',
    submittedAt: '2026-02-12T08:00:00Z',
    reviewedAt: '2026-02-14T10:00:00Z',
    reviewerComment: 'Zoom recordings cover this use case adequately.',
  },
];

// ─── Lookup helpers ───────────────────────────────────────────────────────────

const seedToolsMap: Record<string, Tool[]> = {
  nexus: nexusTools,
  orbit: orbitTools,
  cascade: cascadeTools,
};

const seedRequestsMap: Record<string, ApprovalRequest[]> = {
  nexus: nexusRequests,
  orbit: orbitRequests,
  cascade: cascadeRequests,
};

export function getSeedTools(clientId: string): Tool[] {
  return seedToolsMap[clientId] ?? [];
}

export function getSeedRequests(clientId: string): ApprovalRequest[] {
  return seedRequestsMap[clientId] ?? [];
}
