import { Tool, ApprovalRequest } from './types';

export const seedTools: Tool[] = [
  {
    id: 'tool-1',
    name: 'Slack',
    category: 'Communication',
    monthlyCost: 1250,
    seats: 125,
    owner: 'IT',
    renewalDate: '2025-08-15',
    status: 'active',
  },
  {
    id: 'tool-2',
    name: 'Zoom',
    category: 'Communication',
    monthlyCost: 800,
    seats: 100,
    owner: 'IT',
    renewalDate: '2025-07-01',
    status: 'active',
  },
  {
    id: 'tool-3',
    name: 'Loom',
    category: 'Communication',
    monthlyCost: 200,
    seats: 40,
    owner: 'Marketing',
    renewalDate: '2025-09-20',
    status: 'active',
  },
  {
    id: 'tool-4',
    name: 'Asana',
    category: 'Project Management',
    monthlyCost: 1500,
    seats: 80,
    owner: 'Ops',
    renewalDate: '2025-06-10',
    status: 'active',
  },
  {
    id: 'tool-5',
    name: 'Monday.com',
    category: 'Project Management',
    monthlyCost: 1100,
    seats: 60,
    owner: 'Engineering',
    renewalDate: '2025-07-22',
    status: 'review',
  },
  {
    id: 'tool-6',
    name: 'Salesforce',
    category: 'CRM',
    monthlyCost: 4500,
    seats: 50,
    owner: 'Sales',
    renewalDate: '2025-11-30',
    status: 'active',
  },
  {
    id: 'tool-7',
    name: 'HubSpot',
    category: 'CRM',
    monthlyCost: 1800,
    seats: 30,
    owner: 'Marketing',
    renewalDate: '2025-08-05',
    status: 'review',
  },
  {
    id: 'tool-8',
    name: 'Figma',
    category: 'Design',
    monthlyCost: 450,
    seats: 15,
    owner: 'Design',
    renewalDate: '2025-10-12',
    status: 'active',
  },
  {
    id: 'tool-9',
    name: 'Miro',
    category: 'Design',
    monthlyCost: 320,
    seats: 40,
    owner: 'Product',
    renewalDate: '2025-12-01',
    status: 'active',
  },
  {
    id: 'tool-10',
    name: 'Workday',
    category: 'HR',
    monthlyCost: 3200,
    seats: 200,
    owner: 'HR',
    renewalDate: '2026-01-15',
    status: 'active',
  },
  {
    id: 'tool-11',
    name: 'Greenhouse',
    category: 'HR',
    monthlyCost: 950,
    seats: 20,
    owner: 'HR',
    renewalDate: '2025-09-01',
    status: 'active',
  },
  {
    id: 'tool-12',
    name: 'Notion',
    category: 'Docs',
    monthlyCost: 600,
    seats: 120,
    owner: 'Product',
    renewalDate: '2025-06-28',
    status: 'active',
  },
  {
    id: 'tool-13',
    name: 'Confluence',
    category: 'Docs',
    monthlyCost: 750,
    seats: 90,
    owner: 'Engineering',
    renewalDate: '2025-07-15',
    status: 'review',
  },
  {
    id: 'tool-14',
    name: 'DocuSign',
    category: 'Other',
    monthlyCost: 300,
    seats: 10,
    owner: 'Legal',
    renewalDate: '2025-10-30',
    status: 'active',
  },
  {
    id: 'tool-15',
    name: '1Password',
    category: 'Security',
    monthlyCost: 375,
    seats: 125,
    owner: 'IT',
    renewalDate: '2025-08-01',
    status: 'active',
  },
];

export const seedRequests: ApprovalRequest[] = [
  {
    id: 'req-1',
    toolName: 'Linear',
    category: 'Project Management',
    useCase: 'Engineering issue tracking — cleaner than Asana for dev workflows',
    estimatedMonthlyCost: 400,
    urgency: 'high',
    requester: 'Alex Chen',
    status: 'pending',
    submittedAt: '2025-05-28T10:00:00Z',
  },
  {
    id: 'req-2',
    toolName: 'Grammarly Business',
    category: 'Other',
    useCase: 'Writing quality improvement for customer-facing content',
    estimatedMonthlyCost: 150,
    urgency: 'low',
    requester: 'Sarah Park',
    status: 'approved',
    submittedAt: '2025-05-15T14:30:00Z',
    reviewedAt: '2025-05-17T09:00:00Z',
    reviewerComment: 'Approved — fits within team budget.',
  },
  {
    id: 'req-3',
    toolName: 'Pitch',
    category: 'Design',
    useCase: 'Sales deck creation — faster than Google Slides',
    estimatedMonthlyCost: 200,
    urgency: 'medium',
    requester: 'Marcus Johnson',
    status: 'denied',
    submittedAt: '2025-05-10T11:00:00Z',
    reviewedAt: '2025-05-12T16:00:00Z',
    reviewerComment: 'We already have Figma for presentations. Consolidate there.',
  },
  {
    id: 'req-4',
    toolName: 'Calendly',
    category: 'Other',
    useCase: 'External meeting scheduling for sales team',
    estimatedMonthlyCost: 120,
    urgency: 'medium',
    requester: 'Jamie Torres',
    status: 'pending',
    submittedAt: '2025-06-01T08:00:00Z',
  },
];
