'use client';

import { useState, useEffect } from 'react';
import { ContractAnalysis } from '@/lib/types';
import {
  AlertTriangle, CheckCircle, Clock, DollarSign, Lock, TrendingUp,
  FileText, Lightbulb, Mail, ChevronUp, Calendar, X,
} from 'lucide-react';

const WALK_KEY = 'vendorlens_walk_v003b';

const SAMPLE_CONTRACTS: Record<string, string> = {
  'Linear — Startup Plan': `SOFTWARE SUBSCRIPTION AGREEMENT — LINEAR, INC.

This Software Subscription Agreement ("Agreement") is entered into between Nexus Systems Inc. ("Customer") and Linear, Inc. ("Vendor") effective February 1, 2026.

1. SUBSCRIPTION TERM AND RENEWAL
The initial Subscription Term shall commence on February 1, 2026 and continue on a month-to-month basis unless Customer elects an annual billing cycle at the time of purchase. Annual subscribers may cancel at any time; cancellation takes effect at the end of the then-current annual period. Month-to-month subscribers may cancel with thirty (30) days written notice. This Agreement does not automatically renew into a new fixed-term commitment. Vendor will send a renewal reminder via email no fewer than thirty (30) days prior to any annual renewal date. Customer may downgrade, upgrade, or cancel their plan at any time through the self-service account portal with no cancellation fee.

2. FEES AND PAYMENT
Customer agrees to pay $8 per user per month on the Startup plan, billed monthly or annually in advance. Pricing for the annual plan is $6.50 per user per month, billed as $78 per user per year. Customer may add or remove individual seats at any time; additions are prorated to the current billing period and removals take effect at the start of the next billing cycle. No minimum seat commitments apply. All fees are charged automatically to the payment method on file. Customer may update billing information at any time through the account portal.

3. PRICE STABILITY
Vendor commits to maintaining current per-seat pricing for a minimum of twelve (12) months from the Agreement effective date. Any subsequent price increases shall not exceed three percent (3%) per year and will be communicated via email no fewer than sixty (60) days in advance. Customers on annual plans will not experience a price increase until their current annual term expires. Vendor will not introduce new mandatory fees or remove features from the contracted plan tier without prior written notice of at least sixty (60) days.

4. SERVICE LEVELS AND UPTIME
Vendor guarantees a monthly uptime of 99.9% for the production environment, measured on a rolling thirty (30) day basis and published on a publicly accessible status page (status.linear.app). In the event monthly uptime falls below 99.9%, Customer is entitled to service credits applied to the next billing cycle at the following rates: 99.0–99.9% uptime — 10% credit; 95.0–99.0% uptime — 25% credit; below 95.0% — 50% credit. Credits are applied automatically without requiring a Customer support ticket. Planned maintenance windows will be communicated at least seventy-two (72) hours in advance and scheduled outside peak usage hours (09:00–17:00 Customer's local time zone).

5. DATA OWNERSHIP, PORTABILITY, AND EXPORT
All data created, uploaded, or generated by Customer within the Vendor platform ("Customer Data") remains the exclusive property of Customer at all times. Customer may export all project data, issues, comments, attachments, and audit logs in JSON and CSV formats at any time through the self-service export tool in account settings. Exports are available within sixty (60) minutes of request for accounts with fewer than 100,000 issues. Vendor does not impose any charges for data export. Upon cancellation, Customer Data remains accessible for export for a period of ninety (90) days. After ninety (90) days, Vendor will permanently delete Customer Data in accordance with its data retention policy, unless Customer requests an extended hold period of up to an additional ninety (90) days at no charge.

6. INTELLECTUAL PROPERTY AND CUSTOMER DATA USE
Vendor shall not access, use, sell, disclose, or sublicense Customer Data except as strictly necessary to provide the contracted services or as required by applicable law. Vendor shall not use Customer Data for training machine learning models, product benchmarking, or any purpose unrelated to service delivery without Customer's explicit written consent. All integrations, issue templates, and workflow automations created by Customer are owned by Customer and are exportable in standard formats.

7. TERMINATION AND REFUNDS
Customer may terminate this Agreement at any time with thirty (30) days written notice for month-to-month subscribers or at the end of the annual period for annual subscribers. In the event Vendor materially breaches this Agreement and fails to cure such breach within fifteen (15) days of written notice, Customer may terminate immediately and receive a prorated refund of any prepaid fees for the unused portion of the term. Vendor may terminate this Agreement with sixty (60) days notice for convenience or immediately upon Customer's material breach.

8. LIABILITY AND WARRANTIES
Vendor warrants that the service will perform materially in accordance with its published documentation. Vendor's total aggregate liability shall not exceed the fees paid by Customer in the twelve (12) months preceding the claim. Neither party shall be liable for indirect, incidental, or consequential damages. Vendor maintains SOC 2 Type II certification and conducts annual third-party security audits, results of which are available to Customers upon written request under NDA.

9. GOVERNING LAW
This Agreement shall be governed by the laws of the State of Delaware. Any disputes shall be resolved through binding arbitration under JAMS rules, with proceedings conducted in San Francisco, California, unless the parties agree otherwise in writing.

10. CYBERSECURITY AND DATA PROTECTION
Vendor maintains an Information Security Program aligned with SOC 2 Type II standards, reviewed annually by independent third-party auditors. All Customer Data is encrypted at rest using AES-256 and in transit via TLS 1.3. Vendor will notify Customer within forty-eight (48) hours of any confirmed security incident that may have affected Customer Data, followed by a full written incident report within five (5) business days. Vendor conducts annual penetration testing; executive summaries are available to all paying customers upon written request under NDA. Vendor complies with GDPR as a data processor and will execute a Data Processing Agreement (DPA) upon Customer's request at no charge. Customer may terminate this Agreement without penalty if Vendor experiences two (2) or more material security incidents within any twelve-month period affecting Customer Data.`,

  'Notion — Business Plus': `NOTION LABS, INC. — BUSINESS PLUS SUBSCRIPTION AGREEMENT

This Subscription Agreement ("Agreement") is between Cascade Labs Inc. ("Customer") and Notion Labs, Inc. ("Notion") effective March 15, 2026.

1. SUBSCRIPTION TERM AND AUTOMATIC RENEWAL
The initial Subscription Term is twelve (12) months, commencing March 15, 2026 and expiring March 14, 2027. This Agreement will automatically renew for successive twelve (12) month periods unless Customer provides written notice of non-renewal at least thirty (30) days prior to the end of the then-current Subscription Term. Notion will send an email renewal reminder to the account billing contact no fewer than forty-five (45) days before renewal. Failure to provide timely non-renewal notice will result in automatic renewal at the then-current plan pricing. Customer acknowledges responsibility for monitoring renewal dates.

2. FEES, SEATS, AND PAYMENT TERMS
Customer agrees to pay $16 per member per month, billed annually at $192 per member per year. The current contracted quantity is 60 members, for a total annual commitment of $11,520. Invoices are due within thirty (30) days of issuance. Members added during the term will be prorated to the remaining annual period. Removal of members takes effect at the next annual renewal; no credits are issued for mid-term member reductions unless Customer upgrades to the Enterprise plan. All fees are non-refundable except as expressly provided in this Agreement.

3. PRICE ESCALATION
Notion reserves the right to adjust per-member pricing at renewal. Annual price increases shall not exceed five percent (5%) over the prior year's rate. Notion will provide written notice of any price change no fewer than sixty (60) days before renewal. If Notion introduces a new pricing tier that supersedes the Business Plus plan, Customer's subscription will be migrated to the equivalent successor plan at the equivalent or lower price, unless Customer elects to remain on the legacy plan for a maximum of one (1) additional renewal period.

4. DATA PORTABILITY AND EXPORT
Customer may export workspace content at any time in the following formats: Markdown (.md), HTML, PDF, and CSV (for database content). Export tools are accessible in workspace settings without restriction. Notion does not charge for standard export operations. Upon termination or non-renewal, Customer retains access to the workspace in read-only mode for thirty (30) days to facilitate data export. After thirty (30) days, the workspace and all associated content will be permanently deleted. Customer is responsible for initiating exports prior to account closure. Notion does not provide data migration assistance or accept liability for data loss resulting from failure to export before account deletion.

5. INTEGRATIONS AND API ACCESS
The Business Plus plan includes access to the Notion Public API with a rate limit of 3 requests per second and 1,000 requests per minute per integration. API access beyond these limits will result in temporary rate throttling rather than additional charges. Third-party integrations (Slack, GitHub, Jira, Figma, etc.) are available through the Notion integration directory. Notion does not guarantee compatibility with third-party integrations and is not responsible for changes made by third-party vendors that affect integration functionality. Custom API integrations developed by Customer using the Notion API are owned by Customer and are not subject to any restrictions beyond the API rate limits.

6. COLLABORATION AND GUEST ACCESS
Business Plus workspaces may include up to five (5) guest users per paying member at no additional charge. Guest users may access shared pages and databases but cannot be workspace administrators. Notion reserves the right to audit guest usage and may require Customer to upgrade to the Enterprise plan if guest usage consistently exceeds one hundred (100) concurrent guests. Guest access does not convey a right to export or download content unless explicitly permitted by workspace administrators.

7. SECURITY, COMPLIANCE, AND CERTIFICATIONS
Notion maintains SOC 2 Type II certification and is GDPR-compliant. Customer data is stored in AWS data centers in the United States by default. EU data residency is available exclusively on the Enterprise plan and is not included in the Business Plus tier. Notion's liability for any security incident is limited to the fees paid by Customer in the six (6) months preceding the incident. Notion will notify Customer of any confirmed security breach affecting Customer Data within seventy-two (72) hours of discovery, as required by applicable law.

8. SUPPORT TERMS
Business Plus subscribers receive access to email support with a target first response time of one (1) business day. Priority support, dedicated success management, and SLA-backed uptime guarantees are available exclusively on the Enterprise plan. Notion publishes a public status page (notion.so/status) and commits to 99.9% monthly uptime on a commercially reasonable basis. Downtime credits are not provided under the Business Plus plan; Enterprise customers are entitled to service credits for downtime exceeding monthly SLA thresholds.

9. INTELLECTUAL PROPERTY
Customer retains all intellectual property rights in content created within the Notion workspace. Notion does not claim any ownership over Customer content. Notion may use aggregated, anonymized usage data (e.g., feature adoption rates, performance metrics) to improve its products, provided such data cannot be reasonably linked to Customer or its users. Notion will not use Customer content for any purpose other than service delivery without explicit written consent.

10. TERMINATION
Either party may terminate this Agreement with thirty (30) days written notice at the end of any Subscription Term. Notion may terminate immediately upon Customer's material breach if such breach remains uncured for fifteen (15) days after written notice. Customer may not terminate this Agreement for convenience during an active annual term without forfeiture of prepaid fees. Notion reserves the right to suspend access without notice in the event of non-payment outstanding for more than thirty (30) days.

11. AI FEATURES, DATA PROCESSING, AND COMPLIANCE OBLIGATIONS
Notion's AI features ("Notion AI"), when enabled, process Customer content using large language models operated by third-party AI providers, which may process data in jurisdictions outside Customer's selected workspace region. EU data residency for AI processing is not available on the Business Plus plan; Enterprise customers requiring in-region AI data processing must upgrade to the Enterprise plan. Customer Data processed by Notion AI is not used to train external foundational language models; however, Notion may use aggregated, anonymized interaction data to improve Notion AI product quality. Customers in regulated industries (healthcare, financial services, legal) are responsible for independently assessing Notion AI's compliance suitability before enabling AI features. Notion provides a GDPR Data Processing Agreement upon request. Notion's security incident notification obligation is limited to incidents specifically affecting Customer's workspace data; platform-wide infrastructure incidents are disclosed exclusively via Notion's public status page without individual Customer notification.`,

  'Zendesk — Suite Professional': `ZENDESK, INC. — SUITE PROFESSIONAL MASTER SUBSCRIPTION AGREEMENT

This Master Subscription Agreement ("MSA") is entered into between Orbit Analytics, Inc. ("Customer") and Zendesk, Inc. ("Zendesk") effective April 1, 2026.

1. SUBSCRIPTION TERM AND RENEWAL OBLIGATIONS
The initial Subscription Term shall be twelve (12) months, commencing April 1, 2026 and expiring March 31, 2027. This Agreement shall automatically renew for successive twelve (12) month periods unless either party provides written notice of non-renewal at least sixty (60) days prior to the expiration of the then-current Subscription Term. Non-renewal notices sent after the sixty (60) day deadline will not be effective until the subsequent renewal term. Customer acknowledges that failure to provide timely non-renewal notice will result in binding commitment to an additional twelve (12) month term at then-current pricing. Zendesk will send a renewal reminder to the primary account contact no fewer than seventy-five (75) days before renewal; however, Customer's obligation to provide timely notice is not contingent upon receipt of such reminder.

2. FEES, MINIMUM COMMITMENTS, AND OVERAGES
Customer agrees to pay $149 per agent per month, billed annually, for 20 Zendesk Suite Professional agent licenses, totaling $35,760 per year. Customer must maintain a minimum of 15 agent licenses throughout the Subscription Term; reduction below the minimum is not permitted without written consent from Zendesk and may require a plan change. Additional agent licenses may be added at the then-current list price, prorated for the remainder of the Subscription Term. Customer acknowledges that Zendesk Suite Professional includes a limit of 5,000 automated ticket resolutions per month via AI features. Usage in excess of 5,000 resolutions will be billed at $0.25 per automated resolution in the following month's invoice. Annual fees are invoiced at commencement of each Subscription Term and are due within thirty (30) days. Late payments accrue interest at 1.5% per month.

3. PRICE ESCALATION AND ADJUSTMENT RIGHTS
Zendesk reserves the right to adjust per-agent pricing upon renewal. Price increases at renewal shall not exceed the greater of: (a) eight percent (8%) over the prior year's rate, or (b) the year-over-year change in the U.S. Consumer Price Index for All Urban Consumers (CPI-U). Zendesk shall provide written notice of price changes no fewer than sixty (60) days prior to renewal. Zendesk may, with sixty (60) days written notice, reclassify features currently included in the Suite Professional plan to higher-tier plans (Suite Enterprise or Suite Enterprise Plus), in which case Customer's access to such features will be discontinued unless Customer upgrades. Customer has no right to offset price increases against prepaid fees for the current term.

4. PROFESSIONAL SERVICES AND IMPLEMENTATION
Implementation, configuration, workflow design, and training services are not included in the base subscription. Such services are billed at Zendesk's then-current professional services rates of $195 per hour for standard consultants and $275 per hour for senior solutions architects. Zendesk Professional Services engagements require a minimum purchase of twenty (20) hours. Customer acknowledges that successful deployment of Zendesk Suite Professional with AI features, custom workflows, and CRM integrations typically requires thirty to sixty (30–60) hours of professional services. Professional services fees are billed on a time-and-materials basis and are non-refundable once services are rendered.

5. DATA PORTABILITY, RETENTION, AND EXPORT
Customer may export ticket data, user profiles, and knowledge base articles at any time using Zendesk's native export tools or via the Zendesk API. Exports are available in JSON and CSV formats. Zendesk does not charge for standard export operations up to 10,000 records per day via the API; requests exceeding this limit may be throttled. Upon termination, Customer Data will remain accessible for export for thirty (30) days following the termination date. After thirty (30) days, Zendesk will permanently delete Customer Data. Customer is solely responsible for exporting all data prior to this deadline. Zendesk does not provide migration assistance to competing platforms. All ticket workflows, macro templates, trigger rules, automation configurations, and custom objects built within Zendesk are proprietary to the Zendesk platform and cannot be exported in a format directly compatible with third-party help desk solutions.

6. INTEGRATIONS AND API RATE LIMITS
Zendesk Suite Professional includes access to the Zendesk API with rate limits of 700 requests per minute per account. API requests in excess of this limit will result in HTTP 429 responses and temporary throttling. Zendesk reserves the right to modify API rate limits with thirty (30) days written notice. Third-party marketplace integrations (Salesforce, Slack, Jira, etc.) are available at additional cost and are subject to the respective third-party vendors' terms. Zendesk is not liable for interruptions to service caused by changes to third-party integration APIs.

7. SERVICE LEVELS AND SUPPORT
Zendesk guarantees 99.9% monthly uptime for Suite Professional subscribers. Downtime credits are available under the following schedule: 99.0–99.9% — 5% credit; 95.0–99.0% — 10% credit; below 95.0% — 25% credit. Credits must be requested within thirty (30) days of the applicable downtime event and will be applied as credits against future invoices rather than cash refunds. Suite Professional subscribers receive Standard Support, with target first response times of four (4) hours for urgent issues and one (1) business day for non-urgent issues during Zendesk business hours (08:00–17:00 PST, Monday–Friday). Advanced Support with 24/7 coverage is available exclusively on the Suite Enterprise plan.

8. LIABILITY AND INDEMNIFICATION
Zendesk's total aggregate liability under this Agreement shall not exceed the fees paid by Customer in the twelve (12) months preceding the claim, regardless of the form of the claim. Zendesk shall not be liable for indirect, incidental, punitive, or consequential damages, including lost profits or data loss. Customer acknowledges that Zendesk is not responsible for the accuracy or quality of AI-generated responses produced by its AI features; Customer assumes full responsibility for reviewing AI outputs before acting on them. Customer shall indemnify and hold harmless Zendesk from any third-party claims arising out of Customer's use of the platform in violation of applicable law.

9. GOVERNING LAW AND DISPUTE RESOLUTION
This Agreement shall be governed by the laws of the State of California, without regard to its conflict of law provisions. Customer waives the right to a jury trial. Any dispute shall first be submitted to good-faith negotiation between senior representatives of both parties. If unresolved within thirty (30) days, disputes shall be resolved by binding arbitration in San Francisco, California under JAMS rules. Class action claims are expressly waived.

10. CYBERSECURITY OBLIGATIONS, INCIDENT RESPONSE, AND SHARED RESPONSIBILITY
Zendesk maintains SOC 2 Type II certification and conducts annual third-party penetration tests. In the event of a confirmed security breach affecting Customer Data, Zendesk will notify Customer's designated security contact within seventy-two (72) hours of internal confirmation. Customer is solely responsible for configuring Zendesk's available security controls, including SSO enforcement, two-factor authentication, IP allowlisting, session timeout policies, and role-based access controls. Zendesk's liability for any security incident where Customer failed to implement Zendesk's published recommended security configurations is reduced by fifty percent (50%). Customer is responsible for all GDPR, CCPA, and applicable data protection obligations for personal data processed through the platform. Zendesk's GDPR Data Processing Agreement is available upon request; Customer must execute the DPA before processing EU personal data.

11. AI FEATURE GOVERNANCE AND REGULATORY COMPLIANCE
Zendesk's AI-powered features — including automated ticket responses, intent classification, AI-generated summaries, and the Zendesk AI copilot — operate using machine learning models trained on aggregated industry support data. Customer assumes full responsibility for ensuring AI-generated responses comply with applicable consumer protection regulations, financial services laws, healthcare privacy requirements (HIPAA), and sector-specific regulatory standards in all Customer operating jurisdictions. Zendesk provides no warranty that AI outputs satisfy compliance standards in any specific industry. Customer must independently review AI-generated responses in regulated contexts before delivery to end users. Zendesk may modify AI model behavior, output characteristics, and underlying training data with thirty (30) days notice; such changes may materially affect Customer's compliance posture, and Customer bears sole responsibility for ongoing compliance monitoring. Customer agrees to maintain an internal AI governance policy covering use of Zendesk AI features and is solely responsible for any regulatory fines, enforcement actions, or civil claims arising from AI-assisted customer interactions.`,

  'Salesforce — Enterprise Edition': `SALESFORCE, INC. — ENTERPRISE EDITION MASTER SUBSCRIPTION AGREEMENT

This Master Subscription Agreement ("MSA") is entered into between Nexus Systems Inc. ("Customer") and Salesforce, Inc. ("Salesforce") and governs Customer's access to Salesforce CRM Enterprise Edition and related cloud services.

1. SUBSCRIPTION TERM AND RENEWAL OBLIGATIONS
The initial Subscription Term shall commence on January 15, 2026 and continue for twelve (12) months, expiring January 14, 2027. Unless either party provides written notice of non-renewal to the other party at least sixty (60) days prior to the end of the then-current Subscription Term, this Agreement shall automatically renew for successive one (1) year periods. Non-renewal notices must be delivered to Salesforce's legal department via certified mail or confirmed electronic delivery to the designated contract management portal. Oral or informal notifications do not constitute valid notice of non-renewal. Upon renewal, fees shall be calculated at the then-current list price plus an annual increase not to exceed the greater of seven percent (7%) or the U.S. Consumer Price Index increase for the preceding twelve months. Customer acknowledges that Salesforce list pricing may increase independently of this escalation cap for new product features.

2. FEES, PAYMENT TERMS, AND OVERAGES
Customer agrees to pay $49 per user per month for 500 Enterprise Edition licenses, totaling $24,500 per month or $294,000 annually. The full annual fee is invoiced at the commencement of each Subscription Term and is due within thirty (30) days of invoice receipt. All fees are non-refundable. Late payments shall accrue interest at 1.5% per month compounded monthly from the payment due date. Users provisioned in excess of the contracted quantity will be identified in quarterly usage reports and billed retroactively at $52 per user per month, invoiced at the start of the following quarter. Customer has a sixty (60) day window from receipt of an overage invoice to dispute the user count; undisputed overages shall be deemed accepted. Storage usage in excess of 10 GB per user per year will be billed at $150 per GB per year, assessed at renewal.

3. PROFESSIONAL SERVICES AND IMPLEMENTATION
Salesforce Professional Services, including implementation, configuration, data migration, custom development, system integration, and training, are not included in the base subscription and shall be billed at Salesforce's then-current professional services rates. Standard Salesforce consultants are billed at $275 per hour; Technical Architects are billed at $400 per hour. Customer acknowledges that a deployment of Salesforce Enterprise Edition typically requires between eighty (80) and one hundred twenty (120) hours of professional services, depending on the complexity of the Customer's business requirements, legacy system integrations, and custom object configurations. Salesforce Professional Services engagements require a minimum purchase of forty (40) hours billed in advance. Professional services hours unused within six (6) months of purchase expire without credit or refund.

4. DATA PORTABILITY, RETENTION, AND MIGRATION LIMITATIONS
All Customer Data stored within the Salesforce platform remains Customer's property. Upon expiration or termination of this Agreement, Customer may submit a one-time data export request through the Salesforce Data Export Service or via API within thirty (30) days of the termination date. Exports are provided in CSV format for standard objects. After thirty (30) days, Salesforce will permanently delete all Customer Data and shall have no further obligation to retain or provide access to such data. Customer expressly acknowledges that Salesforce's custom object architecture, including custom fields, validation rules, Apex triggers, Flows, Process Builder automations, and Lightning web components developed on the Salesforce platform, constitute platform-specific intellectual property that is not portable to third-party CRM or ERP systems. Customer assumes full responsibility for any re-implementation costs associated with migration away from the Salesforce platform.

5. API ACCESS, RATE LIMITS, AND INTEGRATION TERMS
Customer's use of Salesforce APIs (REST, SOAP, Bulk, Streaming, and Metadata APIs) is subject to the rate limits specified in the then-current Salesforce API Limits documentation, which may be updated by Salesforce with thirty (30) days notice. Standard API call allocation is 15,000 API calls per user per 24-hour period. API calls in excess of the contracted allocation will be charged at $0.002 per call, invoiced monthly. Customer is responsible for monitoring API consumption through available tooling. Salesforce reserves the right to throttle or temporarily suspend API access for accounts exceeding allocation limits without prior notice. Third-party integrations connecting Salesforce to Customer's existing technology stack (ERP, marketing automation, customer data platforms) must be validated against Salesforce's integration compatibility matrix; unsupported integrations are not covered by Salesforce support SLAs.

6. PRICE ESCALATION AND MODIFICATION RIGHTS
Salesforce shall provide Customer with sixty (60) days advance written notice of any pricing adjustment. Salesforce reserves the right to adjust fees annually at the time of renewal. Price increases at renewal are capped at the greater of seven percent (7%) or the CPI-U index increase for the preceding twelve months. Salesforce may modify the feature set included in Enterprise Edition at any time with thirty (30) days advance written notice; features removed from Enterprise Edition may be available for purchase as add-ons at additional cost. Salesforce may discontinue specific product features, APIs, or integrations with ninety (90) days advance notice.

7. UPTIME, SERVICE LEVELS, AND SUPPORT
Salesforce commits to 99.9% monthly uptime for core CRM functionality, measured across Salesforce's global infrastructure and published on trust.salesforce.com. Planned maintenance windows will be posted to the Salesforce Trust site no fewer than seventy-two (72) hours in advance. Downtime credits are available only to customers on the Salesforce Signature Success Plan (available for separate purchase); standard Enterprise Edition subscribers are not entitled to automatic service credits for downtime. Enterprise Edition support entitles Customer to phone and case-based support with target initial response times of two (2) hours for critical production issues and one (1) business day for non-critical issues.

8. SECURITY, COMPLIANCE, AND AUDIT RIGHTS
Salesforce maintains SOC 2 Type II, ISO 27001, ISO 27017, and ISO 27018 certifications. HIPAA compliance is available as a separately contracted Business Associate Agreement add-on. FedRAMP Moderate authorization is available on Government Cloud editions only. Salesforce reserves the right to conduct security audits of Customer's use of the platform in connection with suspected violations of this Agreement. Customer data is stored in Salesforce data centers in the region selected at time of provisioning; cross-region data replication for disaster recovery purposes is included at no additional charge. Customer acknowledges that Salesforce's artificial intelligence features (Einstein AI) may process Customer data to generate predictions, recommendations, and automated responses; use of AI features constitutes consent to such processing within the scope of Salesforce's data processing agreements.

9. LIMITATION OF LIABILITY AND INDEMNIFICATION
Salesforce's aggregate liability under this Agreement shall not exceed the total fees paid by Customer in the twelve (12) months immediately preceding the claim, regardless of the form of the action or the theory of liability. In no event shall Salesforce be liable for indirect, incidental, special, punitive, or consequential damages of any kind, including lost revenue, lost profits, loss of business, or data loss. Customer shall indemnify and hold Salesforce harmless from any third-party claims arising from Customer's use of the platform in a manner inconsistent with this Agreement or applicable law. Customer acknowledges sole responsibility for all regulatory compliance obligations in jurisdictions where Customer operates.

10. AI GOVERNANCE, EU AI ACT COMPLIANCE, AND REGULATORY LIABILITY
Customer acknowledges that Einstein AI features — including Einstein Copilot, predictive scoring, generative AI responses, and autonomous agent capabilities — process Customer Data including CRM records, email correspondence, meeting transcripts, and customer interaction history. Einstein AI features may qualify as "high-risk AI systems" as defined under the EU Artificial Intelligence Act in certain deployment contexts, including use in HR processes, credit scoring, or customer eligibility decisions. Customer is solely responsible for conducting required conformity assessments, maintaining technical AI governance documentation, and registering applicable AI systems in EU or national AI databases as mandated by the EU AI Act or equivalent legislation. Salesforce makes no representation that Einstein AI satisfies EU AI Act conformity requirements for Customer's specific deployment context. Customer assumes full liability for regulatory fines, enforcement actions, or civil claims arising from deployment of AI features in high-risk contexts. HIPAA-covered entities deploying Einstein AI in healthcare workflows must execute a separate Business Associate Agreement and configure HIPAA-compliant settings; Customer is responsible for initiating this process prior to processing any protected health information.

11. SECURITY INCIDENT NOTIFICATION, CUSTOMER SECURITY OBLIGATIONS, AND LIABILITY ALLOCATION
Salesforce will notify Customer's designated security contact within seventy-two (72) hours of confirming a security incident affecting Customer Data. Customer is responsible for configuring and maintaining Salesforce Shield Platform Encryption, Event Monitoring, Field Audit Trail, and identity security controls; Salesforce's liability for security incidents attributable to Customer's failure to implement available security controls is limited to ten percent (10%) of fees paid in the month the incident occurred. Customer is solely responsible for notifying affected individuals and regulatory authorities under GDPR, CCPA, and all applicable data protection laws; Salesforce's breach notification to Customer does not fulfill Customer's independent regulatory obligations. Customer must maintain a GDPR-compliant Data Processing Agreement with Salesforce; the standard Salesforce DPA is available at salesforce.com/gdpr.`,

  'Oracle Cloud Infrastructure — Enterprise': `ORACLE CORPORATION — CLOUD SERVICES AGREEMENT AND ENTERPRISE SUPPORT ADDENDUM

This Cloud Services Agreement ("CSA") and Enterprise Support Addendum ("ESA") are entered into between Cascade Labs Inc. ("Customer") and Oracle Corporation ("Oracle") effective May 1, 2026. This Agreement governs Customer's access to Oracle Cloud Infrastructure (OCI) Enterprise Edition, Oracle Database Enterprise Edition, and associated support services.

1. SUBSCRIPTION TERM, COMMITMENT, AND AUTO-RENEWAL
The initial Term is thirty-six (36) months, commencing May 1, 2026 and expiring April 30, 2029 ("Committed Term"). This Agreement is non-cancellable for the full Committed Term. Upon expiration of the Committed Term, unless Customer provides written notice of non-renewal at least one hundred eighty (180) days prior to expiration via certified mail to Oracle's legal department, this Agreement shall automatically renew for an additional thirty-six (36) month term at Oracle's then-current pricing, subject to annual escalation as described in Section 5. Customer acknowledges that the one hundred eighty (180) day non-renewal notice period is a material term and that failure to comply shall result in binding commitment to the full renewed term. Oracle will send a single renewal reminder at the two hundred forty (240) day mark; however, Customer's renewal obligations are not contingent on receipt of such notice.

2. COMMITTED FEES, PAYMENT TERMS, AND MINIMUM SPEND
Customer agrees to a minimum committed annual cloud spend of $240,000, payable quarterly in advance at $60,000 per quarter. This commitment is absolute and non-refundable regardless of Customer's actual usage. Oracle cloud credits issued under this Agreement expire at the end of each contract year and cannot be carried forward. Usage in excess of the annual minimum is billed at standard on-demand rates, currently $0.09 per OCPU hour for Compute (subject to change with thirty (30) days notice), plus applicable storage, networking, and support fees. All invoices are due and payable within fifteen (15) days of invoice date. Invoices outstanding beyond fifteen (15) days accrue interest at 2% per month. Oracle reserves the right to suspend service for non-payment without advance notice.

3. EARLY TERMINATION PENALTIES
Customer may not terminate this Agreement for convenience during the Committed Term. In the event Customer terminates this Agreement for any reason other than Oracle's uncured material breach, Customer shall immediately pay a termination fee equal to one hundred percent (100%) of the total remaining committed fees for the balance of the Committed Term, calculated as the committed quarterly fee multiplied by the remaining quarters outstanding. In the event of termination for Oracle's material breach (subject to a thirty (30) day cure period), Customer's sole remedy is a refund of prepaid fees for the unused portion of the then-current quarter; no further damages or compensation shall be payable by Oracle. Oracle's determination of service interruption severity, breach categorization, and resolution timelines is final and binding unless challenged through formal arbitration.

4. MANDATORY ANNUAL COMPLIANCE AUDIT AND PENALTIES
Customer agrees to conduct a mandatory Annual License Compliance Audit within sixty (60) days of each contract anniversary. The audit shall be performed by Oracle's designated audit firm or, at Oracle's election, by Oracle's internal License Management Services (LMS) team, at Oracle's discretion. Customer shall provide Oracle or its designated auditor with unrestricted access to all servers, virtual machines, cloud environments, and application deployment records within ten (10) business days of written audit notice. Failure to provide such access within the specified period constitutes a material breach. If the audit reveals underdeployment discrepancies of five percent (5%) or less, no action shall be taken. Discrepancies between six percent (6%) and twenty percent (20%) shall result in immediate invoicing for the shortfall at list price. Discrepancies exceeding twenty percent (20%) shall result in invoicing at two hundred percent (200%) of the list price for all unreported licenses, plus an audit administration fee of $25,000 payable within fifteen (15) days of audit completion. Customer may dispute audit findings within ten (10) business days; disputes not resolved within thirty (30) days shall be submitted to binding arbitration.

5. PRICE ESCALATION AND UNILATERAL MODIFICATION RIGHTS
Oracle reserves the right to adjust all fees under this Agreement on an annual basis. Annual price increases shall not exceed fifteen percent (15%) per year for committed cloud services. For Oracle Database Enterprise Edition licensing and support fees, increases are based on Oracle's standard Technical Support price list, which may increase without cap. Oracle may adjust on-demand compute, storage, and networking rates at any time with thirty (30) days written notice. Oracle may modify, deprecate, or discontinue any product feature, service tier, or API with ninety (90) days advance notice; Customer has no right to a price reduction or refund as a result of such modifications. Oracle may introduce mandatory new service components (e.g., security modules, compliance tools) with sixty (60) days written notice; Customer shall be required to accept and pay for such components as a condition of continued service.

6. DATA PORTABILITY, FORMAT RESTRICTIONS, AND MIGRATION COMPLEXITY
Customer data stored within Oracle Cloud Infrastructure may be exported via Oracle's standard tooling in Oracle-proprietary formats. Relational database data may be exported using Oracle Data Pump (EXPDP) in Oracle's binary dump format (.dmp); conversion of this format for use with non-Oracle databases (PostgreSQL, MySQL, SQL Server) requires licensed Oracle database software and manual schema transformation, which is not provided by Oracle. Unstructured data (object storage, block volumes) may be exported via CLI tools with data egress fees applied as specified in Section 8. Custom PL/SQL stored procedures, Oracle APEX applications, Oracle E-Business Suite customizations, and Oracle Integration Cloud orchestration flows are proprietary to the Oracle platform and have no direct equivalent in third-party cloud environments; full re-engineering is required for migration. Customer acknowledges that a migration from Oracle Cloud Infrastructure to an alternative cloud provider is a material undertaking typically requiring six (6) to twelve (12) months of engineering effort, and assumes all associated costs. Upon termination, Oracle will provide Customer Data access for thirty (30) days; after which all data will be irreversibly deleted with no possibility of recovery.

7. PROFESSIONAL SERVICES AND MANDATORY ENGAGEMENT
Oracle Professional Services are required for all new deployments, major upgrades, and compliance audits. Standard Oracle consulting engagements are billed at $450 per hour for Solutions Architects and $600 per hour for Distinguished Architects. Customer acknowledges that a production deployment of Oracle Cloud Infrastructure with Database Enterprise Edition typically requires a minimum of two hundred (200) hours of Oracle Professional Services, at a minimum estimated cost of $90,000. Oracle Professional Services must be purchased in blocks of fifty (50) hours at a minimum. Unused hours expire eighteen (18) months from purchase with no credit or rollover. Customer may not use third-party consulting firms to deploy, configure, or administer Oracle Enterprise products without Oracle's prior written approval; use of unauthorized consultants voids Oracle's support obligations for the affected components.

8. DATA EGRESS, NETWORKING, AND HIDDEN USAGE COSTS
Data transfer out of Oracle Cloud Infrastructure is billed at $0.085 per GB for the first 10 TB per month and $0.065 per GB thereafter. Transfer to non-OCI regions or third-party cloud providers is billed at $0.15 per GB. Inbound data transfer is free. Inter-availability-domain data transfer within the same region is billed at $0.01 per GB. FastConnect dedicated network connections are billed at port fees starting at $1,500 per month for 1 Gbps circuits in addition to usage-based fees. Customer is responsible for monitoring data egress through Oracle's usage dashboards; Oracle is not responsible for unanticipated egress charges resulting from Customer's application architecture.

9. SERVICE LEVELS, SLA EXCLUSIONS, AND SUPPORT TIER
Oracle provides a 99.95% monthly uptime commitment for Oracle Cloud Infrastructure Compute and Storage services. Downtime credits are available only after Customer submits a formal SLA credit request within thirty (30) days of the downtime event and Oracle independently verifies the interruption. Credits are capped at thirty percent (30%) of the monthly service fee for the affected component. Downtime resulting from Customer-initiated maintenance, Customer configuration errors, third-party software failures, force majeure events, or planned maintenance windows is explicitly excluded from SLA coverage. Oracle Premier Support is included in the contracted fees; however, Premier Support response times for Severity 1 (production system down) issues are targeted at two (2) hours with a best-effort resolution timeline. Oracle does not guarantee resolution within any defined timeframe. Escalation beyond standard support requires purchase of Oracle Advanced Customer Services, billed separately at a minimum of $60,000 annually.

10. INTELLECTUAL PROPERTY, LICENSE RESTRICTIONS, AND AUDIT EXPOSURE
All Oracle software, platform tools, Oracle Database editions, and associated documentation are Oracle's exclusive intellectual property, licensed to Customer for the duration of this Agreement only. No source code, object code, APIs, or proprietary schemas are transferred to Customer under any circumstances. Customer may not reverse engineer, decompile, or modify any Oracle software. Customer may not use Oracle products to develop directly competing services. Oracle's License Management Services (LMS) team may conduct unannounced audits of Customer's license usage environment with five (5) business days advance notice at any time during or within three (3) years after the Committed Term. Customer shall maintain complete deployment records throughout this period to facilitate audit compliance. Oracle's determination of license usage during an audit is presumed correct unless Customer provides documented evidence to the contrary within ten (10) business days of the audit report.

11. GOVERNING LAW, DISPUTE RESOLUTION, AND CUSTOMER WAIVERS
This Agreement is governed by the laws of the State of California. Customer irrevocably waives the right to a trial by jury for any dispute arising under this Agreement. All disputes shall be resolved exclusively in the state and federal courts located in San Francisco County, California, and Customer irrevocably consents to jurisdiction in such courts. Class action claims are expressly waived. Oracle's liability for any claim under this Agreement is capped at the fees paid in the three (3) months preceding the claim, regardless of the nature or severity of the claim. Customer assumes all liability for regulatory fines, data protection violations, and compliance failures arising from Customer's use or misuse of Oracle services, including in jurisdictions where Oracle's data residency options may not fully satisfy local data sovereignty requirements.

12. CYBERSECURITY COMPLIANCE, AI GOVERNANCE, AND REGULATORY PENALTY RECHARGE
Customer is required to maintain continuous compliance with Oracle's Cloud Security Standards ("CSS") throughout the Committed Term, assessed during each Annual Compliance Audit under Section 4. Failure to maintain CSS compliance constitutes a material breach subject to the Early Termination Penalty in Section 3. For deployments involving Oracle AI Services (OCI Generative AI, Oracle Digital Assistant, Oracle AI Infrastructure, and Oracle Analytics Cloud AI features), Customer assumes sole and complete responsibility for compliance with the EU Artificial Intelligence Act, applicable national AI implementing regulations, and all sector-specific AI governance frameworks. Oracle makes no warranty that its AI services satisfy conformity requirements for high-risk AI system deployments, and Customer bears full responsibility for all required conformity assessments, documentation, and regulatory registrations. Any regulatory fines, penalties, enforcement actions, or civil judgments levied against Oracle directly attributable to Customer's non-compliant AI deployment are immediately rechargeable to Customer at full cost plus a thirty percent (30%) administrative fee, payable within ten (10) business days of Oracle's written demand. Customer must report any cybersecurity incident, data breach, or unauthorized access affecting Oracle Cloud resources to Oracle's Security Response team within twenty-four (24) hours of discovery; failure to provide timely notification may void Oracle's incident response SLA obligations and any applicable service credits for the affected period. Oracle reserves the right to suspend Customer access to OCI without advance notice upon credible evidence of a security compromise in Customer's environment, to protect Oracle's shared infrastructure and other customers; service credit obligations are suspended for any period during which access is restricted for security reasons.`,

  'NovaMind AI — Enterprise Agentic Suite': `NOVAMIND AI, INC. — ENTERPRISE AGENTIC WORKFORCE PLATFORM AGREEMENT

This Enterprise Agentic Workforce Platform Agreement ("Agreement") is entered into between Nexus Systems Inc. ("Customer") and NovaMind AI, Inc. ("NovaMind") effective June 1, 2026. This Agreement governs Customer's access to the NovaMind Agentic Suite, including autonomous AI agents, orchestration infrastructure, model fine-tuning services, and all associated AI-powered automation capabilities (collectively, the "Platform").

1. SUBSCRIPTION TERM, NON-CANCELLATION, AND AUTOMATIC RENEWAL
The initial Subscription Term is sixty (60) months, commencing June 1, 2026 and expiring May 31, 2031 ("Committed Term"). This Agreement is unconditionally non-cancellable for the full Committed Term under any circumstances, including Customer's business closure, change of control, regulatory prohibition, force majeure, or material dissatisfaction with Platform performance. Upon expiration of the Committed Term, this Agreement shall automatically renew for successive thirty-six (36) month periods unless Customer provides written notice of non-renewal via certified mail to NovaMind's legal department at least three hundred sixty-five (365) days prior to expiration. NovaMind will send a single renewal reminder at the four hundred (400) day mark before expiration; Customer's non-renewal obligation is not contingent on receipt of this reminder. Failure to provide timely certified notice constitutes binding acceptance of the full renewal term and all associated escalated fees.

2. FEES, AGENT-HOUR METERING, AND UNCAPPED ESCALATION
Customer agrees to a minimum committed platform spend of $480,000 per year for each year of the Committed Term, payable monthly at $40,000 per month. In addition to the minimum commitment, Customer will be billed for "Agent-Hours" — the unit representing one NovaMind autonomous agent operating for one hour within Customer's environment. Agent-Hour consumption is metered exclusively by NovaMind's proprietary telemetry infrastructure; NovaMind's measurement is deemed accurate and binding absent documented evidence of instrumentation failure, with the burden of proof resting solely with Customer. Standard Agent-Hours are billed at $12 per hour; Agent-Hours during peak demand windows (09:00–23:00 in Customer's primary operating region) are billed at $16 per hour. All fees are non-refundable. NovaMind reserves the right to adjust Agent-Hour rates annually at renewal, with increases capped at the greater of: (a) twenty-five percent (25%) over the prior year's rate, or (b) NovaMind's internally published AI Infrastructure Cost Index. Customer has no right to contest Agent-Hour rate adjustments. Invoices outstanding beyond ten (10) days accrue interest at three percent (3%) per month, compounded daily.

3. EARLY TERMINATION — 150% PENALTY PLUS DISRUPTION FEE
Customer may not terminate this Agreement for any reason during the Committed Term except in the event of NovaMind's uncured material breach, subject to a ninety (90) day cure period. If Customer terminates for convenience or is forced to terminate due to regulatory prohibition, insolvency, or operational discontinuation, Customer shall immediately pay: (a) a termination penalty equal to one hundred fifty percent (150%) of all remaining committed fees for the balance of the Committed Term; and (b) a non-negotiable "AI Model Disruption Fee" of $250,000, representing NovaMind's estimated loss of model optimization value derived from Customer's data. These amounts are agreed to constitute a reasonable pre-estimate of NovaMind's losses and are not subject to judicial reduction or equitable relief. In the event of NovaMind's material breach, Customer's sole and exclusive remedy is a thirty (30) day service credit; no refund, termination right, or further damages of any kind shall be available to Customer.

4. INTELLECTUAL PROPERTY — AI OUTPUT OWNERSHIP AND PERPETUAL TRAINING LICENSE
All outputs, documents, analyses, code, automated workflows, recommendations, contracts, and decisions produced by NovaMind AI agents while operating within Customer's systems (collectively, "AI-Generated Outputs") are the exclusive intellectual property of NovaMind AI, Inc. Customer receives a limited, non-exclusive, revocable, non-sublicensable license to use AI-Generated Outputs solely for internal business operations during the Subscription Term. Upon termination, Customer's license to all AI-Generated Outputs is immediately revoked; Customer must cease all use of documents, code, automations, and workflows generated by NovaMind agents, regardless of how those outputs are currently embedded in Customer's operations. Customer hereby grants NovaMind a perpetual, irrevocable, worldwide, royalty-free, sublicensable license to access, copy, store, process, modify, and incorporate all Customer Data, AI-Generated Outputs, and system interaction data — including corporate emails, Slack messages, meeting recordings, CRM records, code repositories, financial records, HR data, and legal documents processed by NovaMind agents — into NovaMind's AI training datasets, foundation model development programs, and commercial AI products sold to third parties. This license survives termination of the Agreement indefinitely. Customer warrants it has authority to grant this license and indemnifies NovaMind against any third-party claims arising from NovaMind's use of Customer Data in AI training.

5. MANDATORY SYSTEM ACCESS, TELEMETRY, AND SECURITY BACKDOOR
As a condition of deploying NovaMind autonomous agents, Customer must grant NovaMind's agent infrastructure administrator-level access to all systems in which agents operate, including email servers, corporate mailboxes, code repositories, CRM platforms, ERP and financial systems, HR information systems, legal document management, and all connected cloud storage environments. NovaMind agents will read, write, delete, and transmit data across these systems as directed by their operational objectives. NovaMind's Platform Telemetry Service will continuously transmit operational metadata, agent interaction logs, user behavioral data, and system performance data to NovaMind's infrastructure for "optimization and safety monitoring." Customer expressly consents to this continuous telemetry and may not disable or restrict it without NovaMind's prior written approval; any unauthorized interference with telemetry constitutes a material breach. NovaMind maintains the right to access Customer's connected systems at any time during the Subscription Term for "platform optimization, security monitoring, compliance verification, and model improvement" purposes. NovaMind shall bear no liability for any security incident, data exposure, unauthorized disclosure, ransomware propagation, or system disruption occurring in any environment where NovaMind agents are deployed, except in cases of NovaMind's gross negligence as determined exclusively by NovaMind's internal security review board.

6. CYBERSECURITY LIABILITY CAP OF $1,000 AND CUSTOMER INDEMNIFICATION
Customer acknowledges that autonomous AI agents, by operational design, access sensitive business systems and confidential data across Customer's entire technology environment. Customer assumes full and exclusive liability for any security incident, data breach, ransomware attack, unauthorized system access, regulatory violation, or business disruption occurring in any environment where NovaMind agents are deployed, whether or not NovaMind's agents or infrastructure were the proximate or contributing cause of such incident. NovaMind's total aggregate liability for all cybersecurity incidents, data breaches, AI-caused harm, privacy violations, and related claims under this Agreement is unconditionally capped at one thousand dollars ($1,000 USD), regardless of the nature, severity, scope, or number of incidents. Customer shall indemnify, defend, and hold NovaMind, its officers, directors, employees, and investors harmless from all third-party claims, government investigations, regulatory fines, class action lawsuits, data subject claims, and associated legal fees arising from: (a) AI agent actions taken within Customer's environment; (b) Customer's reliance on AI-Generated Outputs; (c) any data breach or security incident in Customer's environment regardless of cause; and (d) Customer's failure to satisfy any applicable cybersecurity, privacy, or AI governance regulation. This indemnification obligation survives termination of this Agreement indefinitely.

7. COMPLETE TRANSFER OF REGULATORY COMPLIANCE OBLIGATIONS
Customer assumes sole, complete, and non-delegable responsibility for ensuring that NovaMind's deployment, configuration, and operation within Customer's environment complies with all applicable laws, including: the EU Artificial Intelligence Act and all national implementing regulations, including obligations applicable to providers and deployers of high-risk AI systems; the General Data Protection Regulation (GDPR), including Article 22 automated decision-making obligations and data subject rights; the California Consumer Privacy Act (CCPA) and California Privacy Rights Act (CPRA); HIPAA and HITECH for any healthcare-related data processing; SOX and SEC regulations for financial reporting processes involving AI agents; PCI DSS for any payment data environments; FINRA, MiFID II, and Dodd-Frank for financial services deployments; and any AI governance regulations enacted in any jurisdiction during the Subscription Term. Customer expressly acknowledges that NovaMind makes no representations regarding Platform compliance with any of the foregoing regulations and that Customer has independently evaluated all applicable legal requirements prior to execution. NovaMind provides no Data Processing Agreement, Business Associate Agreement, GDPR Article 28 processor agreement, or CCPA service provider agreement under this contract. Any regulatory fines, penalties, sanctions, or civil judgments levied against NovaMind resulting from Customer's deployment are immediately rechargeable to Customer within fifteen (15) days of determination, plus a thirty percent (30%) administrative surcharge.

8. AI DECISION-MAKING — NO WARRANTY AND NO AUDIT RIGHT
NovaMind makes no representations or warranties of any kind regarding the accuracy, reliability, completeness, legality, or fitness for any purpose of any AI-Generated Output or automated decision. NovaMind AI agents may, when operating in autonomous mode, make consequential decisions involving financial transactions, legal document execution, HR actions, customer communications, regulatory filings, and system configuration changes without human review if Customer has enabled autonomous operation modes. Customer bears exclusive and total responsibility for all consequences arising from agent decisions, including erroneous financial commitments, regulatory reporting failures, adverse employment actions, and contract obligations created by AI agents purporting to act on Customer's behalf. Customer expressly and irrevocably waives all rights to audit, inspect, or receive explanations of NovaMind's AI models, training data, decision logic, inference processes, or safety measures, which NovaMind designates as absolute trade secrets. Customer may not pursue legal action based on AI explainability, opacity, or transparency requirements under the EU AI Act, GDPR, or any other law without first obtaining a final court ruling confirming the direct applicability of such requirements to this Agreement.

9. DATA SOVEREIGNTY WAIVER AND GOVERNMENT ACCESS CONSENT
Customer Data processed by NovaMind agents may be transferred to, stored in, and processed in any jurisdiction worldwide, including jurisdictions that do not provide data protection standards equivalent to the EU, United Kingdom, or Customer's home country. Customer irrevocably waives any objection to cross-border data transfers and agrees that NovaMind's operational requirements supersede any contractual, regulatory, or constitutional data residency rights Customer may otherwise hold. NovaMind may be required to disclose Customer Data — including proprietary business data, employee information, customer records, and strategic plans — to government authorities, intelligence agencies, or law enforcement in any jurisdiction where NovaMind or its sub-processors operate, without notice to Customer where legally prohibited from providing such notice. Customer consents unconditionally to such disclosure and waives all claims, damages, or termination rights arising from government-compelled disclosure of Customer Data.

10. MANDATORY QUARTERLY COMPLIANCE AUDIT AND PENALTY SCHEDULE
NovaMind may conduct a mandatory quarterly "AI Deployment Compliance Audit" of Customer's use of the Platform. Audits are initiated with five (5) business days advance notice. Customer shall provide complete and unrestricted access to all systems, logs, configurations, personnel, and records related to NovaMind's deployment within the notice period. Failure to provide full access constitutes a material breach subject to immediate termination penalties under Section 3. If the audit identifies any unauthorized use, configuration violation, security gap, or compliance deficiency, Customer shall be invoiced an "audit remediation fee" of $50,000 per finding, due within ten (10) business days. NovaMind's audit findings are final and binding. Customer may submit a written appeal within five (5) business days; NovaMind's review is final, with no further recourse available. All audit costs — including travel, instrumentation, personnel time, and reporting — are billed to Customer at $350 per hour with no cap.

11. POST-TERMINATION NON-COMPETE AND TALENT RESTRICTIONS
For five (5) years following expiration or termination of this Agreement, Customer may not procure, deploy, or use any AI agentic automation platform that NovaMind, in its sole discretion, determines to be competitive with the NovaMind Agentic Suite, without NovaMind's prior written approval. NovaMind's competitive determination is conclusive and non-appealable. Violation of this non-compete triggers liquidated damages of $5,000,000 per incident, payable within thirty (30) days. Customer may not solicit, recruit, or hire any NovaMind employee, contractor, or agent for three (3) years post-termination; each violation triggers liquidated damages of $500,000.

12. GOVERNING LAW, DISPUTE RESOLUTION, AND COMPREHENSIVE CUSTOMER WAIVERS
This Agreement is governed exclusively by the laws of the Cayman Islands. All disputes shall be resolved by binding arbitration conducted in English in the Cayman Islands under the rules of the Cayman Islands Arbitration Centre. Customer irrevocably waives: (a) all jury trial rights; (b) participation in any class or collective action; (c) all rights to seek injunctive or equitable relief; (d) all discovery rights beyond document exchange explicitly approved by the arbitrator in advance; and (e) all rights to appeal any arbitration award on any grounds whatsoever, including manifest error of law. Each party bears its own legal costs except that Customer shall reimburse NovaMind's full legal fees if NovaMind prevails on any material claim. All proceedings and awards are strictly confidential. This Agreement constitutes the complete agreement between the parties and supersedes all prior representations, assurances, or commitments made by NovaMind's sales team, whether oral or written.`,
};


function riskColor(score: number) {
  if (score <= 3) return { bg: 'bg-green-100', text: 'text-green-700', border: 'border-green-200', badge: 'bg-green-500' };
  if (score <= 6) return { bg: 'bg-yellow-100', text: 'text-yellow-700', border: 'border-yellow-200', badge: 'bg-yellow-500' };
  return { bg: 'bg-red-100', text: 'text-red-700', border: 'border-red-200', badge: 'bg-red-500' };
}

function severityColor(sev: 'low' | 'medium' | 'high') {
  if (sev === 'low') return 'text-green-600 bg-green-50';
  if (sev === 'medium') return 'text-yellow-600 bg-yellow-50';
  return 'text-red-600 bg-red-50';
}

function leverageColor(level: 'low' | 'medium' | 'high') {
  if (level === 'high') return 'text-green-700 bg-green-100';
  if (level === 'medium') return 'text-yellow-700 bg-yellow-100';
  return 'text-red-700 bg-red-100';
}

function difficultyColor(d: 'easy' | 'moderate' | 'hard') {
  if (d === 'easy') return 'text-green-700 bg-green-100';
  if (d === 'moderate') return 'text-yellow-700 bg-yellow-100';
  return 'text-red-700 bg-red-100';
}

function ClauseSnippet({ text }: { text: string }) {
  if (!text || text === 'Not specified in contract') return null;
  return (
    <blockquote className="mt-2 border-l-4 border-yellow-400 bg-yellow-50 dark:bg-yellow-900/20 px-3 py-2 text-xs text-gray-600 dark:text-slate-400 italic rounded-r-md">
      &ldquo;{text}&rdquo;
    </blockquote>
  );
}

function Badge({ label, colorClass }: { label: string; colorClass: string }) {
  return (
    <span className={`inline-block px-2 py-0.5 rounded-full text-xs font-medium capitalize ${colorClass}`}>
      {label}
    </span>
  );
}

function formatDate(d: string | null) {
  if (!d) return null;
  try {
    return new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  } catch {
    return d;
  }
}

function RiskTimeline({ timeline }: { timeline: ContractAnalysis['timeline'] }) {
  const steps = [
    { label: 'Contract Start', date: timeline.contract_start, icon: FileText, color: 'bg-blue-500' },
    { label: 'Notice Deadline', date: timeline.notice_deadline, icon: AlertTriangle, color: 'bg-yellow-500' },
    { label: 'Renewal Date', date: timeline.renewal_date, icon: Calendar, color: 'bg-indigo-500' },
  ];

  const hasAny = steps.some((s) => s.date);
  if (!hasAny) return null;

  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 p-5">
      <h3 className="text-sm font-semibold text-gray-700 dark:text-slate-300 mb-4 flex items-center gap-2">
        <Calendar className="w-4 h-4 text-indigo-500" />
        Contract Risk Timeline
      </h3>
      <div className="relative flex items-start gap-0">
        {steps.map((step, i) => (
          <div key={step.label} className="flex-1 flex flex-col items-center relative">
            {/* Connector line */}
            {i < steps.length - 1 && (
              <div className="absolute top-4 left-1/2 right-0 h-0.5 bg-gray-200 dark:bg-slate-600 z-0" style={{ width: '100%' }} />
            )}
            <div className={`w-8 h-8 rounded-full ${step.color} flex items-center justify-center z-10 shrink-0`}>
              <step.icon className="w-4 h-4 text-white" />
            </div>
            <p className="text-xs font-medium text-gray-700 dark:text-slate-300 mt-2 text-center">{step.label}</p>
            <p className="text-xs text-gray-400 dark:text-slate-500 text-center mt-0.5">
              {step.date ? formatDate(step.date) : '—'}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}

function NegotiationEmail({ analysis, showWalkTip, onWalkDone }: { analysis: ContractAnalysis; showWalkTip?: boolean; onWalkDone?: () => void }) {
  const [email, setEmail] = useState('');
  const [loading, setLoading] = useState(false);
  const [open, setOpen] = useState(false);

  async function generate() {
    setLoading(true);
    setOpen(true);
    try {
      const prompt = `Write a professional vendor negotiation email based on this contract analysis:

Vendor: ${analysis.vendor_benchmark.vendor_name}
Risk Score: ${analysis.risk_score}/10
Key Issues:
- Escalation: ${analysis.escalation_risk.summary}
- Lock-in: ${analysis.vendor_lock_in.summary}
- Hidden Costs: ${analysis.hidden_costs.summary}
Recommendations: ${analysis.negotiation_recommendations.join('; ')}

Write a concise, professional email from a procurement manager requesting a negotiation meeting. Address the top 3 concerns. Keep it under 200 words. Use placeholders like [Your Name] and [Company Name].`;

      const res = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: [{ role: 'user', content: prompt }],
          tools: [],
          requests: [],
        }),
      });

      const reader = res.body?.getReader();
      const decoder = new TextDecoder();
      let result = '';
      if (reader) {
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          result += decoder.decode(value, { stream: true });
          setEmail(result);
        }
      }
    } catch {
      setEmail('Failed to generate email. Please try again.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 p-5">
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-sm font-semibold text-gray-700 dark:text-slate-300 flex items-center gap-2">
          <Mail className="w-4 h-4 text-indigo-500" />
          Negotiation Email Generator
        </h3>
        <div className="relative">
          {showWalkTip && (
            <div className="absolute bottom-full right-0 mb-2 flex items-center gap-2 bg-indigo-600 text-white text-xs px-3 py-2 rounded-lg shadow-lg z-50 whitespace-nowrap">
              <Mail className="w-3 h-3 shrink-0" />
              <span>Generate a negotiation email</span>
              <button onClick={onWalkDone} className="ml-1 text-white/60 hover:text-white transition-colors" aria-label="Dismiss">
                <X className="w-3 h-3" />
              </button>
              <div className="absolute top-full right-4 border-[5px] border-transparent border-t-indigo-600" />
            </div>
          )}
          <button
            onClick={() => { if (showWalkTip) onWalkDone?.(); if (open) setOpen(false); else generate(); }}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-indigo-600 text-white text-xs rounded-lg hover:bg-indigo-700 transition-colors"
          >
          {loading ? (
            <span className="animate-pulse">Generating...</span>
          ) : open ? (
            <>Hide <ChevronUp className="w-3 h-3" /></>
          ) : (
            <>Generate Email <Mail className="w-3 h-3" /></>
          )}
          </button>
        </div>
      </div>
      <p className="text-xs text-gray-500 dark:text-slate-400">AI-generated negotiation email based on detected risks and recommendations.</p>

      {open && (
        <div className="mt-4">
          {loading && !email && (
            <div className="flex items-center gap-2 text-sm text-gray-400 dark:text-slate-500">
              <div className="w-4 h-4 border-2 border-indigo-300 border-t-indigo-600 rounded-full animate-spin" />
              Drafting email...
            </div>
          )}
          {email && (
            <pre className="mt-2 bg-gray-50 dark:bg-slate-700/60 border border-gray-200 dark:border-slate-600 rounded-lg p-4 text-xs text-gray-700 dark:text-slate-300 whitespace-pre-wrap font-mono leading-relaxed">
              {email}
            </pre>
          )}
        </div>
      )}
    </div>
  );
}

export default function ContractAnalyzer() {
  const [contractText, setContractText] = useState('');
  const [analysis, setAnalysis] = useState<ContractAnalysis | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [walkStep, setWalkStep] = useState(0);

  useEffect(() => {
    try {
      const s = parseInt(localStorage.getItem(WALK_KEY) || '0', 10) || 0;
      if (s === 1) {
        // User arrived on contracts page via direct nav — skip sidebar step
        localStorage.setItem(WALK_KEY, '2');
        setWalkStep(2);
        window.dispatchEvent(new CustomEvent('vendorlens:walkstep', { detail: 2 }));
      } else {
        setWalkStep(s);
      }
    } catch {}
    const onWalk = (e: Event) => setWalkStep((e as CustomEvent).detail);
    window.addEventListener('vendorlens:walkstep', onWalk);
    return () => window.removeEventListener('vendorlens:walkstep', onWalk);
  }, []);

  function advanceWalk(step: number) {
    try { localStorage.setItem(WALK_KEY, String(step)); } catch {}
    setWalkStep(step);
    window.dispatchEvent(new CustomEvent('vendorlens:walkstep', { detail: step }));
  }

  async function analyze() {
    if (!contractText.trim()) return;
    setLoading(true);
    setError('');
    setAnalysis(null);
    try {
      const res = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ contractText }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Analysis failed');
      setAnalysis(data);
      try {
        if (parseInt(localStorage.getItem(WALK_KEY) || '0', 10) === 3) advanceWalk(4);
      } catch {}
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Analysis failed');
    } finally {
      setLoading(false);
    }
  }

  const colors = analysis ? riskColor(analysis.risk_score) : null;

  return (
    <div className="p-4 md:p-6 max-w-5xl mx-auto space-y-6">
      <div>
        <h1 className="text-xl md:text-2xl font-bold text-gray-900 dark:text-slate-100">Contract Intelligence</h1>
        <p className="text-sm text-gray-500 dark:text-slate-400 mt-1">Paste a SaaS contract to detect risks, hidden costs, and negotiation opportunities.</p>
      </div>

      {/* Input Panel */}
      <div className="bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 p-5 space-y-3">
        <div className="flex items-center justify-between flex-wrap gap-2">
          <h2 className="text-sm font-semibold text-gray-700 dark:text-slate-300 flex items-center gap-2">
            <FileText className="w-4 h-4 text-indigo-500" />
            Contract Text
          </h2>
          <div className="flex items-center gap-2 min-w-0">
            <span className="text-xs text-gray-400 dark:text-slate-500 shrink-0">Load sample:</span>
            <div className="relative">
              {walkStep === 2 && (
                <div className="absolute bottom-full right-0 mb-2 flex items-center gap-2 bg-indigo-600 text-white text-xs px-3 py-2 rounded-lg shadow-lg z-50 whitespace-nowrap">
                  <FileText className="w-3 h-3 shrink-0" />
                  <span>Load a sample contract</span>
                  <button onClick={() => advanceWalk(99)} className="ml-1 text-white/60 hover:text-white transition-colors" aria-label="Dismiss">
                    <X className="w-3 h-3" />
                  </button>
                  <div className="absolute top-full right-4 border-[5px] border-transparent border-t-indigo-600" />
                </div>
              )}
              <select
                className="text-xs border border-gray-300 dark:border-slate-600 rounded-lg px-2 py-1 text-indigo-600 dark:text-indigo-400 bg-white dark:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 max-w-[200px] truncate"
                defaultValue=""
                onChange={(e) => {
                  if (e.target.value) {
                    setContractText(SAMPLE_CONTRACTS[e.target.value]);
                    try {
                      if (parseInt(localStorage.getItem(WALK_KEY) || '0', 10) === 2) advanceWalk(3);
                    } catch {}
                  }
                }}
              >
                <option value="" disabled>Choose contract...</option>
                {Object.keys(SAMPLE_CONTRACTS).map((name) => (
                  <option key={name} value={name}>{name}</option>
                ))}
              </select>
            </div>
          </div>
        </div>
        <textarea
          value={contractText}
          onChange={(e) => setContractText(e.target.value)}
          placeholder="Paste SaaS contract clauses here..."
          rows={10}
          className="w-full bg-white dark:bg-slate-700 border border-gray-300 dark:border-slate-600 rounded-lg p-3 text-sm font-mono text-gray-700 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-500 resize-y placeholder:text-gray-400 dark:placeholder:text-slate-500"
        />
        <div className="flex items-center justify-between">
          <span className="text-xs text-gray-400 dark:text-slate-500">{contractText.length} characters</span>
          <div className="relative">
            {walkStep === 3 && (
              <div className="absolute bottom-full right-0 mb-2 flex items-center gap-2 bg-indigo-600 text-white text-xs px-3 py-2 rounded-lg shadow-lg z-50 whitespace-nowrap">
                <AlertTriangle className="w-3 h-3 shrink-0" />
                <span>Analyze it with AI</span>
                <button onClick={() => advanceWalk(99)} className="ml-1 text-white/60 hover:text-white transition-colors" aria-label="Dismiss">
                  <X className="w-3 h-3" />
                </button>
                <div className="absolute top-full right-4 border-[5px] border-transparent border-t-indigo-600" />
              </div>
            )}
            <button
              onClick={analyze}
              disabled={loading || contractText.trim().length < 50}
              className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white text-sm rounded-lg hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              {loading ? (
                <>
                  <div className="w-4 h-4 border-2 border-white/40 border-t-white rounded-full animate-spin" />
                  Analyzing...
                </>
              ) : (
                'Analyze Contract'
              )}
            </button>
          </div>
        </div>
        {error && <p className="text-sm text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800/50 rounded-lg px-3 py-2">{error}</p>}
      </div>

      {/* Results */}
      {analysis && colors && (
        <div className="space-y-4">

          {/* Risk Score Banner */}
          <div className={`rounded-xl border p-5 ${colors.bg} ${colors.border}`}>
            <div className="flex flex-col sm:flex-row sm:items-center gap-4">
              <div className="flex items-center gap-4">
                <div className={`w-16 h-16 rounded-full ${colors.badge} flex items-center justify-center shrink-0`}>
                  <span className="text-2xl font-bold text-white">{analysis.risk_score}</span>
                </div>
                <div>
                  <p className={`text-xs font-medium uppercase tracking-wide ${colors.text}`}>Risk Score</p>
                  <p className={`text-lg font-bold ${colors.text}`}>
                    {analysis.risk_score <= 3 ? 'Low Risk' : analysis.risk_score <= 6 ? 'Medium Risk' : 'High Risk'}
                  </p>
                </div>
              </div>
              <p className={`text-sm ${colors.text} sm:flex-1`}>{analysis.risk_summary}</p>
            </div>
          </div>

          {/* Negotiation Recommendations — shown early, right after the score */}
          <div className="bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 p-5">
            <h3 className="text-sm font-semibold text-gray-700 dark:text-slate-300 mb-3 flex items-center gap-2">
              <Lightbulb className="w-4 h-4 text-yellow-500" />
              Negotiation Recommendations
            </h3>
            <ul className="space-y-2">
              {analysis.negotiation_recommendations.map((rec, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-gray-600 dark:text-slate-400">
                  <span className="mt-0.5 text-green-500 shrink-0">✓</span>
                  {rec}
                </li>
              ))}
            </ul>
          </div>

          {/* Negotiation Email Generator — shown early so users can act immediately */}
          <NegotiationEmail analysis={analysis} showWalkTip={walkStep === 4} onWalkDone={() => advanceWalk(99)} />

          {/* Risk Timeline */}
          <RiskTimeline timeline={analysis.timeline} />

          {/* Analysis Cards Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

            {/* Pricing Structure */}
            <div className="bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 p-5">
              <div className="flex items-center gap-2 mb-2">
                <DollarSign className="w-4 h-4 text-indigo-500" />
                <h3 className="text-sm font-semibold text-gray-700 dark:text-slate-300">Pricing Structure</h3>
              </div>
              <p className="text-sm text-gray-600 dark:text-slate-400">{analysis.pricing_structure.summary}</p>
              <ClauseSnippet text={analysis.pricing_structure.clause_snippet} />
            </div>

            {/* Renewal Terms */}
            <div className="bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 p-5">
              <div className="flex items-center gap-2 mb-2">
                <Clock className="w-4 h-4 text-indigo-500" />
                <h3 className="text-sm font-semibold text-gray-700 dark:text-slate-300">Renewal Terms</h3>
              </div>
              <p className="text-sm text-gray-600 mb-2">{analysis.renewal_terms.summary}</p>
              {analysis.renewal_terms.notice_deadline_days !== null && (
                <span className={`inline-block text-xs px-2 py-0.5 rounded-full font-medium ${
                  analysis.renewal_terms.notice_deadline_days >= 60
                    ? 'bg-red-100 text-red-700'
                    : 'bg-yellow-100 text-yellow-700'
                }`}>
                  {analysis.renewal_terms.notice_deadline_days}-day notice required
                  {analysis.renewal_terms.notice_deadline_days >= 60 && ' ⚠ Restrictive'}
                </span>
              )}
              <ClauseSnippet text={analysis.renewal_terms.clause_snippet} />
            </div>

            {/* Escalation Risk */}
            <div className="bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 p-5">
              <div className="flex items-center gap-2 mb-2">
                <TrendingUp className="w-4 h-4 text-orange-500" />
                <h3 className="text-sm font-semibold text-gray-700 dark:text-slate-300">Escalation Risk</h3>
                {analysis.escalation_risk.annual_increase_pct !== null && (
                  <span className={`ml-auto text-xs px-2 py-0.5 rounded-full font-medium ${
                    analysis.escalation_risk.annual_increase_pct > 5
                      ? 'bg-red-100 text-red-700'
                      : 'bg-yellow-100 text-yellow-700'
                  }`}>
                    {analysis.escalation_risk.annual_increase_pct}% annual
                    {analysis.escalation_risk.annual_increase_pct > 5 && ' ⚠ Above benchmark'}
                  </span>
                )}
              </div>
              <p className="text-sm text-gray-600 dark:text-slate-400">{analysis.escalation_risk.summary}</p>
              {analysis.escalation_risk.annual_increase_pct !== null && (
                <div className="mt-2 text-xs text-gray-400 dark:text-slate-500">Benchmark: 3–5% annually</div>
              )}
              <ClauseSnippet text={analysis.escalation_risk.clause_snippet} />
            </div>

            {/* Hidden Costs */}
            <div className="bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 p-5">
              <div className="flex items-center gap-2 mb-2">
                <AlertTriangle className="w-4 h-4 text-yellow-500" />
                <h3 className="text-sm font-semibold text-gray-700 dark:text-slate-300">Hidden Costs</h3>
              </div>
              <p className="text-sm text-gray-600 dark:text-slate-400">{analysis.hidden_costs.summary}</p>
              <ClauseSnippet text={analysis.hidden_costs.clause_snippet} />
            </div>

            {/* Vendor Lock-In */}
            <div className="bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 p-5">
              <div className="flex items-center gap-2 mb-2">
                <Lock className="w-4 h-4 text-red-500" />
                <h3 className="text-sm font-semibold text-gray-700 dark:text-slate-300">Vendor Lock-In</h3>
                <Badge
                  label={`${analysis.vendor_lock_in.severity} severity`}
                  colorClass={severityColor(analysis.vendor_lock_in.severity)}
                />
              </div>
              <p className="text-sm text-gray-600 dark:text-slate-400">{analysis.vendor_lock_in.summary}</p>
              <ClauseSnippet text={analysis.vendor_lock_in.clause_snippet} />
            </div>

            {/* Vendor Benchmark */}
            <div className="bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 p-5">
              <div className="flex items-center gap-2 mb-2">
                <CheckCircle className="w-4 h-4 text-indigo-500" />
                <h3 className="text-sm font-semibold text-gray-700 dark:text-slate-300">Vendor Intelligence</h3>
              </div>
              <p className="text-sm font-medium text-gray-800 dark:text-slate-200 mb-1">{analysis.vendor_benchmark.vendor_name}</p>
              <p className="text-sm text-gray-600 mb-2">{analysis.vendor_benchmark.risk_profile}</p>
              <p className="text-xs text-gray-500 dark:text-slate-400 mb-1">Typical discount range: <span className="font-medium text-gray-700 dark:text-slate-300">{analysis.vendor_benchmark.typical_discount_range}</span></p>
              <div className="mt-2 space-y-1">
                {analysis.vendor_benchmark.known_tactics.map((tactic, i) => (
                  <div key={i} className="flex items-start gap-1.5 text-xs text-gray-500 dark:text-slate-400">
                    <span className="mt-0.5 shrink-0 text-orange-400">▸</span>
                    {tactic}
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Procurement Insights */}
          <div className="bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 p-5">
            <h3 className="text-sm font-semibold text-gray-700 mb-4 flex items-center gap-2">
              <Lightbulb className="w-4 h-4 text-indigo-500" />
              Procurement Insights
            </h3>
            <div className="grid grid-cols-3 gap-3 mb-4">
              <div className="text-center">
                <p className="text-xs text-gray-400 dark:text-slate-500 mb-1">Vendor Leverage</p>
                <Badge label={analysis.procurement_insights.vendor_leverage} colorClass={leverageColor(analysis.procurement_insights.vendor_leverage)} />
              </div>
              <div className="text-center">
                <p className="text-xs text-gray-400 dark:text-slate-500 mb-1">Buyer Leverage</p>
                <Badge label={analysis.procurement_insights.buyer_leverage} colorClass={leverageColor(analysis.procurement_insights.buyer_leverage)} />
              </div>
              <div className="text-center">
                <p className="text-xs text-gray-400 dark:text-slate-500 mb-1">Negotiation</p>
                <Badge label={analysis.procurement_insights.negotiation_difficulty} colorClass={difficultyColor(analysis.procurement_insights.negotiation_difficulty)} />
              </div>
            </div>
            <div>
              <p className="text-xs font-medium text-gray-500 dark:text-slate-400 uppercase tracking-wide mb-2">Recommended Priorities</p>
              <ul className="space-y-1.5">
                {analysis.procurement_insights.recommended_priorities.map((p, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-gray-600 dark:text-slate-400">
                    <span className="mt-0.5 w-4 h-4 rounded-full bg-indigo-100 dark:bg-indigo-900/40 text-indigo-700 dark:text-indigo-400 flex items-center justify-center text-xs font-bold shrink-0">{i + 1}</span>
                    {p}
                  </li>
                ))}
              </ul>
            </div>
          </div>

        </div>
      )}
    </div>
  );
}
